### ISSUE TITLE
How about RefineDet_Res101_VOC results?

### ISSUE THREAD

**Issue by youngwanLEE** [sfzhang15/RefineDet#10]
Hi, I think your RefineDet is very impressive result.

I wonder the accuracy and FPS of RefineDet_Res101_VOC_512.

Have you tried it ?

**Comment by sfzhang15** [comment]
@youngwanLEE Hi, We have not tried training RefineDet_Res101_VOC_512 yet, but we have the plan to train them. The FPS of RefineDet_Res101_VOC_512 is about 8 On Titan X (maxwell) with batch size 1.

**Comment by junjieAI** [comment]
@youngwanLEE 
Hi, have you trained RefineDet_Res101_VOC_512?

**Comment by sfzhang15** [comment]
@junjieAI Hi, so far, we have not trained RefineDet_Res101_VOC_512 yet, since we are busy with another work. After RefineDet is published, we will improve this work. At that time we will try to train RefineDet_Res101_VOC_512.

**Comment by junjieAI** [comment]
@sfzhang15 
I get it, I have just finished VGG_VOC_512 training, and prepare to do further test!

**Comment by junjieAI** [comment]
@sfzhang15 
Get it, I have just finished VGG_VOC_512 training, and prepare to do further test!

**Comment by junjieAI** [comment]
@sfzhang15 
Another problem maybe needs you help.Have you tried different 'base_lr' and 'lr_policy', as during my training process, after 160k iterations, the loss decrease from 20 to 3-4, and still higher(use your scripts parameters,base_lr: 4.99999987369e-05,lr_policy: "multistep")

**Comment by sfzhang15** [comment]
@junjieAI Hi, since limited time and computing resources, we have not tried different 'base_lr' and 'lr_policy', these parameters are the same as SSD.
