### ISSUE TITLE
Out of memory problem is easier to appear for GTX1080Ti GPU

### ISSUE THREAD

**Issue by marearth** [sfzhang15/RefineDet#102]
Two images per gpu is allowed to run for GTX1080Ti GPU while 5 images per gpu is allowed for TitanXP based on the paper. As a matter of fact,the gap of memory volume between two kinds of gpu is just 1G.  Minibatch  can only be set in a small scale for GTX1080Ti  ,or there are out of memory problems. I wonder whether there are some tricks to deal with

**Comment by sfzhang15** [comment]
@marearth 
"Two images per gpu is allowed to run for GTX1080Ti GPU while 5 images per gpu is allowed for TitanXP based on the paper.", please describe it more clearly, thanks.

**Comment by marearth** [comment]
The minibatch value can be set as 20 in the 4 TianXP gpus environment for RefineNet512(ResNet101) model.However that value can just be set as 8 in the 4 GTX1080Ti gpus environment,or there will be out of memory problems with bigger values.

**Comment by marearth** [comment]
OK,I've got it. Surprisingly, the model can eat so much memory for big model。

**Comment by marearth** [comment]
@sfzhang15 
when evaluating  trained coco RefineNet101_512 model, out of memory problem appeared in the multi scale test configuration. 8 K80 gpus(~88G) still can not overcome the problem. I wonder how you can get through it.

**Comment by sfzhang15** [comment]
@marearth 
We use 12G GPU to do multi scale testing. Maybe 8G is not enough.
