### ISSUE TITLE
About Fig.6 and Fig.7 in papper

### ISSUE THREAD

**Issue by Duankaiwwen** [sfzhang15/RefineDet#106]
Hello @sfzhang15, thanks for your great job! But I have a question. How to plot Fig.6 and Fig.7? I notice their formats are the same as that of SSD. So is the code public or can you share the codes? Thanks!

**Comment by sfzhang15** [comment]
@Duankaiwwen 
https://github.com/weiliu89/detectionAnalysis

**Comment by Duankaiwwen** [comment]
@sfzhang15 Thanks!
