### ISSUE TITLE
Lighter backbone network model？

### ISSUE THREAD

**Issue by ymchen7** [sfzhang15/RefineDet#108]
Hi, Shifeng

Firstly, thanks for sharing this solid work. As you mentioned that the digits reported are trained with 4 M40(24GB). Since I only got 2 M40(12GB), the batchsize is limited to reach a good convergence. Have you trained using a lighter backbone, e.g. Res18/50?  Is the performance deteriorated?

**Comment by sfzhang15** [comment]
@ymchen7 
Sorry, we do not train RefineDet using Res18/50. You can try it. We think the performance will deteriorate.
