### ISSUE TITLE
Check failed: std::equal(top_shape.begin() + 1, top_shape.begin() + 4, shape.begin() + 1) 

### ISSUE THREAD

**Issue by lzh19961031** [sfzhang15/RefineDet#112]
F0819 18:28:22.517751 20648 annotated_data_layer.cpp:205] Check failed: std::equal(top_shape.begin() + 1, top_shape.begin() + 4, shape.begin() + 1) 
*** Check failure stack trace: ***
    @     0x7f3d9ab215cd  google::LogMessage::Fail()
    @     0x7f3d9ab23433  google::LogMessage::SendToLog()
    @     0x7f3d9ab2115b  google::LogMessage::Flush()
    @     0x7f3d9ab23e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3da1ca65c0  caffe::AnnotatedDataLayer<>::load_batch()
    @     0x7f3da1ceb5cf  caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7f3da1d4bdd5  caffe::InternalThread::entry()
    @     0x7f3d993df5d5  (unknown)
    @     0x7f3d8c0516ba  start_thread
    @     0x7f3d8bd8741d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

Anyone know how to deal with this?Please help!!!

**Comment by sfzhang15** [comment]
@lzh19961031 
What did you modify?

**Comment by stalagmite7** [comment]
how was this issue resolved?

**Comment by sfzhang15** [comment]
@stalagmite7 
Hi, if the questioner doesn't return to me for two weeks, I will close this issue.

**Comment by shiva13425** [comment]
@sfzhang15 Am working on caffejacinto github repo. trying to train a model for face and person identification. while doing training for 21 classes its fine. I modified the 21 class train prototxt to 3 class by changing certain values. 
while running after modification this issue occured.
Kindly share your comments.
