### ISSUE TITLE
输入图片resize的方法是怎样的

### ISSUE THREAD

**Issue by JimReno** [sfzhang15/RefineDet#113]
万分感谢大佬开源算法代码哈，我在`VGG16_VOC2007_512.py`中对图片进行resize操作的插值方式不是很理解。

命令`caffe_pb2.BlobShape(dim=[1, 3, resize_height, resize_width])])`是暴力地把图片`resize`成512x512的尺寸吗，还是把长边按照图片的长宽比放缩到512,再把短边进行padding呢？此外，对于这两种resize方法，后者不会损坏图片的特征结构，感觉会好一些，我这样理解是否正确呢？

**Comment by sfzhang15** [comment]
@JimReno 
是暴力地把图片resize成512x512，因为训练也是这样做的。

**Comment by JimReno** [comment]
好的，谢谢；）

**Comment by china56321** [comment]
我想把图片缩放到806＊608，在VGG16_VOC2007_320.py将resize_width = 806，resize_height = 608，报以下错误：Check failed: bottom[i]->shape() == bottom[0]->shape() 
*** Check failure stack trace: ***
    @     0x7f8ff2faf0cd  google::LogMessage::Fail()
    @     0x7f8ff2fb0f33  google::LogMessage::SendToLog()
    @     0x7f8ff2faec28  google::LogMessage::Flush()
    @     0x7f8ff2fb1999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8ff378429d  caffe::EltwiseLayer<>::Reshape()
    @     0x7f8ff38ad8bd  caffe::Net<>::Init()
    @     0x7f8ff38af441  caffe::Net<>::Net()
    @     0x7f8ff38b9b52  caffe::Solver<>::InitTrainNet()
    @     0x7f8ff38b9fc6  caffe::Solver<>::Init()
    @     0x7f8ff38ba33a  caffe::Solver<>::Solver()
    @     0x7f8ff36757b3  caffe::Creator_SGDSolver<>()
    @     0x56239fd6749d  train()
    @     0x56239fd63729  main
    @     0x7f8ff167ab97  __libc_start_main
    @     0x56239fd6424a  _start
Aborted (core dumped)
请问只能设高宽设为320＊320或512＊512吗？可以将宽高设为不同值吗？或可以改以上两个宽高值吗？
