### ISSUE TITLE
How do I use your excellent code to train a model on my custom dataset?

### ISSUE THREAD

**Issue by 437432655** [sfzhang15/RefineDet#114]
How do I use your excellent code to train a model on my custom dataset ?

**Comment by 437432655** [comment]
I already transfer my dataset to the format of VOC , including img and xml .

**Comment by sfzhang15** [comment]
@437432655 
You shuold set the anchor scales and aspect ratios according to your datasets. Besides, some parameters of data augmentation maybe need to be modified.
