### ISSUE TITLE
detect  in Videos

### ISSUE THREAD

**Issue by Silencesss** [sfzhang15/RefineDet#118]
Thank you for your good job! 
I have use the train code to train a model in my own dataset ,and I can use the refinedet_demo.py to detect in images,and use the refinedet_test.py to evaluate my train model.
but I want to use the RefineDet to detect  in videos , I don't know how to  modify the code in refinedet_demo.py ,Could you tell me how to do it? or upload a video detection demo?
Thanks!

**Comment by jazzseow** [comment]
@Silencesss 
I think you can try extract the frames from the video, then run the detector over the frames

**Comment by china56321** [comment]
i also  want to use the RefineDet to detect in videos,and i also don't know how to modify the code in refinedet_demo.py ?do you solve it ? can you post the code ?

> Thank you for your good job!
> I have use the train code to train a model in my own dataset ,and I can use the refinedet_demo.py to detect in images,and use the refinedet_test.py to evaluate my train model.
> but I want to use the RefineDet to detect in videos , I don't know how to modify the code in refinedet_demo.py ,Could you tell me how to do it? or upload a video detection demo?
> Thanks!

**Comment by sfzhang15** [comment]
@china56321 
You can refer to [ssd_pascal_video.py](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_pascal_video.py) and [ssd_pascal_webcam.py](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_pascal_webcam.py).
