### ISSUE TITLE
RefileDet_root/examples do not include  a CMakeLists.txt

### ISSUE THREAD

**Issue by TqDavid** [sfzhang15/RefineDet#12]
hi,  when i make this repo,  this argument "add_subdirectory(examples)" in RefineDet_root/CMakeLists.txt need a CMakeLists.txt in Refine_root/examples. Maybe I should comment this line?

**Comment by sfzhang15** [comment]
@TqDavid Hi, you can comment that line, because nothing needs to be compiled in example folder. By the way, we have compiled this repo many times and without comment that line, it also works well.

**Comment by TqDavid** [comment]
Thank you for your reply.It is a great job for object  detection! Thank you.
