### ISSUE TITLE
Still cannot reach accuracy in paper

### ISSUE THREAD

**Issue by lji72** [sfzhang15/RefineDet#120]
1. FIrstly, I do not use pretrain model, the map is only 75%.
2.Secondly, I use pretrain VGG model, and training with VOC 2007 + 2012 trainval data, and test in VOC2007 test data(input size is 320) and use bacthsize 32, 16 and other param from paper, the map raise to 79.20%, but it cannot reach 80% . I will be thankful if you gives some advices.

**Comment by sfzhang15** [comment]
@lji72 
For training with the pretrained model, have you modified something?

**Comment by lji72** [comment]
1. Now map raises, I find something different that my train and test lmdb is resize to 320 and RefineDet provided is original size.   When I use RefineDet provided lmdb, map continues raising.

**Comment by lji72** [comment]
@sfzhang15 Thanks.

**Comment by ZhiqiJiang** [comment]
@sfzhang15 @lji72 I encountered with the same problem. But my mAP was 79.60% that was a little higher than 79.20% and I didn't have the resizing problem as Iji72.

**Comment by sfzhang15** [comment]
@0801130205 
have you modified something? If you do not modify anything, you can refer to [this issue](https://github.com/sfzhang15/RefineDet/issues/153).

**Comment by ZhiqiJiang** [comment]
@sfzhang15 Thank you for your rapid response. I will try it.

**Comment by ZhiqiJiang** [comment]
@sfzhang15 I have reached the accuracy after modified according to [this issue](https://github.com/sfzhang15/RefineDet/issues/153). Thank you for your contribution and guidence.
