### ISSUE TITLE
How to train with only 2 classes?

### ISSUE THREAD

**Issue by YTLT** [sfzhang15/RefineDet#125]
Hi, I  tried to train a network that only detects person. So I deleted other categories in labelmap_voc.prototxt. When I created new LMBD files(I run create_data.sh), there was an error:
Unkown name: cow.

**Comment by peterpaniff** [comment]
> Hi, I tried to train a network that only detects person. So I deleted other categories in labelmap_voc.prototxt. When I created new LMBD files(I run create_data.sh), there was an error:
> Unkown name: cow.

你需要将对应的标注文档xml也给改掉，你的标注xml文档只能出现person

**Comment by YTLT** [comment]
@peterpaniff  I modified the xml files and it worked! thank you!

**Comment by yisiyinheluojiutian** [comment]
> @peterpaniff I modified the xml files and it worked! thank you!

你好，请问具体需要怎么改啊？
