### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by jinfagang** [sfzhang15/RefineDet#127]
There is this error got when start training:
```
F1025 10:10:35.081321 11170 sampler.cpp:89] Check failed: sampler.min_scale() > 0. (0 vs. 0) 
*** Check failure stack trace: ***
    @     0x7fba88a460cd  google::LogMessage::Fail()
    @     0x7fba88a47f33  google::LogMessage::SendToLog()
    @     0x7fba88a45c28  google::LogMessage::Flush()
    @     0x7fba88a48999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fba89169899  caffe::SampleBBox()
    @     0x7fba89169b20  caffe::GenerateSamples()
    @     0x7fba89169d44  caffe::GenerateBatchSamples()
    @     0x7fba89198c38  caffe::AnnotatedDataLayer<>::load_batch()
    @     0x7fba891d7e4f  caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7fba8930ba15  caffe::InternalThread::entry()
    @     0x7fba7af3cbcd  (unknown)
    @     0x7fba6841a6db  start_thread
    @     0x7fba8790988f  clone
Aborted (core dumped)


```

It seems the SSD git repo also get this error, do you have any idea why this error got?

**Comment by sfzhang15** [comment]
@jinfagang 
Maybe you set min_scale in batch_sampler to 0?

**Comment by jinfagang** [comment]
@sfzhang15 Right, I make a mistake. After fix this error, this training process stick to:

```
I1025 17:46:04.900111 27197 solver.cpp:295] Learning Rate Policy: multistep
I1025 17:46:04.924211 27197 blocking_queue.cpp:50] Data layer prefetch queue empty

```

And the cpu usage are 100%, people says it is caused by GPU train more fast than CPU, but I think this is not like that, because I shrinked the batchsize and just can not start the whole training process. Any idea?

**Comment by sfzhang15** [comment]
@jinfagang 
Do you use CPU to train?

**Comment by sfzhang15** [comment]
It is very strange. Your GPU can run other programs successfully?

**Comment by jinfagang** [comment]
@sfzhang15 Yes, the tensorflow or pytorch program can run success. I think it might be something wrong with the data. this indicates that, caffe using cpu read data but it got null. so that GPU are waitting for data. But my lmdb file are generated success (the path is correct and the lmdb file is not empty).

**Comment by sfzhang15** [comment]
@jinfagang 
Do you test the model at beginning? It is strange and I have not met this problem.
