### ISSUE TITLE
where is the Anchor refinement  in ARM？

### ISSUE THREAD

**Issue by hhh151671** [sfzhang15/RefineDet#132]
您好，我想问下，anchor在arm的粗调，是在源码哪一部分，arm 的box是怎么和ODM层联系的，我只找到了初步过滤的hard neg mining那段。
大佬能给讲解下吗，小白刚入caffe，谢谢 抱拳.jpg

**Comment by sfzhang15** [comment]
你好，具体实现请见[这里](https://github.com/sfzhang15/RefineDet/blob/master/src/caffe/util/bbox_util.cpp#L923-L929)

**Comment by hhh151671** [comment]
> 你好，具体实现请见[这里](https://github.com/sfzhang15/RefineDet/blob/master/src/caffe/util/bbox_util.cpp#L923-L929)

懂了，谢谢

**Comment by Edwardmark** [comment]
@hhh151671 @sfzhang15 您好，能告诉我下anchor refine去除多余负anchor的代码在哪儿吗？新人找不到。谢谢了

**Comment by sfzhang15** [comment]
@Edwardmark 
anchor refine去除多余负anchor的[代码](https://github.com/sfzhang15/RefineDet/blob/master/src/caffe/util/bbox_util.cpp#L1104-L1107)
