### ISSUE TITLE
training own datasets, teset phase: out of memory

### ISSUE THREAD

**Issue by gllspeed** [sfzhang15/RefineDet#134]
Hi:
I executed the script VGG16_VOC2007_512.py to train my own data set. The test phase of the training process reported error == cudaSuccess out of memory. The itersize was 1 in test.prototxt and the number of test pictures was 82. There is no problem with executing the script VGG16_VOC2007_320.py. What is the reason, thank you!

**Comment by sfzhang15** [comment]
@gllspeed 
Batch_size=82 may be too large to the 512x512 input size, you can try to use small batch size.
