### ISSUE TITLE
error

### ISSUE THREAD

**Issue by BaiFangyu** [sfzhang15/RefineDet#135]
我想训练我自己的数据集，然后总是抛出这个错误，不知道怎么解决？？
Traceback (most recent call last):
  File "examples/refinedet/VGG16_VOC2007_320.py", line 430, in <module>
    AddExtraLayers(net, use_batchnorm, arm_source_layers, normalizations, lr_mult=lr_mult)
  File "examples/refinedet/VGG16_VOC2007_320.py", line 61, in AddExtraLayers
    DeconvBNLayer(net, from_layer, out_layer, use_batchnorm, False, 256, 2, 0, 2, lr_mult=lr_mult)
NameError: global name 'DeconvBNLayer' is not defined

**Comment by sfzhang15** [comment]
@BaiFangyu 
DeconvBNLayer在[这里](https://github.com/sfzhang15/RefineDet/blob/master/python/caffe/model_libs.py#L87)，你看看是不是编译对了，或import对了caffe的路径没

**Comment by ml930310** [comment]
@BaiFangyu  @sfzhang15 我也出现了相同的问题，编译通过，import 路径为 “/home/**/RefineDet/python/”

**Comment by ml930310** [comment]
@sfzhang15 @BaiFangyu 我也出现了相同的问题，编译通过，import 路径为 “/home/**/RefineDet/python/”  ,但问题依然没有解决，请问怎么解决呢？

**Comment by sfzhang15** [comment]
@BaiFangyu @ml930310 
可以尝试在运行的python文件前头，加入sys.path.insert(0, '../../python')，其中‘../../python’是RefineDet下的python路径。
