### ISSUE TITLE
怎么在windows下使用

### ISSUE THREAD

**Issue by chaobeiying** [sfzhang15/RefineDet#136]
您好，如果我想在windows下使用，可行吗？怎么用呢，谢谢您

**Comment by chaobeiying** [comment]
> @chaobeiying
> 你好，不好意思，我们没有在windows下用过caffe，所以也不大清楚。个人觉得，如果只是前传的话，应该还是比较容易的，如果还要训练的话，可能要改不少东西。

您好，非常感谢您的回复，我不想做训练，在Ubuntu下训练的caffemodel想在Windows下调用。

**Comment by chaobeiying** [comment]
> @chaobeiying
> 如果只是跑测试的话，只要Windows下的caffe配好了，把相关的几个层拷贝过去，应该就可以跑的。

非常感谢您的回复，是，我的思路是这样，但是就是这相关的几个层，我编译通不过，（难过ing），还有一个问题，就是测试的时候，进入test下编译lib，这个的作用是什么呢？我觉得测试的时候貌似没有用到lib里的东西啊！（再次感谢哈）

**Comment by sfzhang15** [comment]
@chaobeiying 
test下的lib包含评测代码，如果只是前传的话，应该不需要。

**Comment by chaobeiying** [comment]
> @chaobeiying
> test下的lib包含评测代码，如果只是前传的话，应该不需要。

非常感谢您的回复，经过两周的折腾的，终于在window下调通了，不过还有个问题，不太明白，就是在Ubuntu下测试，得到的置信度很高，检测结果也可用，但是在windows下得到的置信度很低，不明白为什么这样，
![9257a518-265e-4797-975f-3b1988e7650f](https://user-images.githubusercontent.com/32634125/50064550-c1fcf180-01ec-11e9-8f73-d7c905123d84.png)
![img_20181217_110800_ b 43ddd4b](https://user-images.githubusercontent.com/32634125/50064562-ccb78680-01ec-11e9-899f-2a280aea735d.jpg)
（不知道这样能不能把图片传上去，解释一下图片）第一张图是Windows的测试结果，我打印了一下det_conf的值，基本上都是0.2-0.3之间，而且有很多。第二张图是Ubuntu下的测试结果，con_det只有两个值，而且接近1，（同一张图）。在Windows下我没有训练，就是调用Ubuntu下训练得到的模型。为什么会出现检测结果不正确这种情况。
感谢您。

**Comment by chaobeiying** [comment]
> > > @chaobeiying
> > > test下的lib包含评测代码，如果只是前传的话，应该不需要。
> > 
> > 
> > 非常感谢您的回复，经过两周的折腾的，终于在window下调通了，不过还有个问题，不太明白，就是在Ubuntu下测试，得到的置信度很高，检测结果也可用，但是在windows下得到的置信度很低，不明白为什么这样，
> > ![9257a518-265e-4797-975f-3b1988e7650f](https://user-images.githubusercontent.com/32634125/50064550-c1fcf180-01ec-11e9-8f73-d7c905123d84.png)
> > ![img_20181217_110800_ b 43ddd4b](https://user-images.githubusercontent.com/32634125/50064562-ccb78680-01ec-11e9-899f-2a280aea735d.jpg)
> > （不知道这样能不能把图片传上去，解释一下图片）第一张图是Windows的测试结果，我打印了一下det_conf的值，基本上都是0.2-0.3之间，而且有很多。第二张图是Ubuntu下的测试结果，con_det只有两个值，而且接近1，（同一张图）。在Windows下我没有训练，就是调用Ubuntu下训练得到的模型。为什么会出现检测结果不正确这种情况。
> > 感谢您。
> 
> 您好，我也遇到这样的问题，而且如果是五类的话，所有的响应值都是处在这个范围内，不知道是哪里的问题？您解决了吗？

没有解决，你也是移植到Windows下了吗？

**Comment by wolfworld6** [comment]
> > > > @chaobeiying
> > > > test下的lib包含评测代码，如果只是前传的话，应该不需要。
> > > 
> > > 
> > > 非常感谢您的回复，经过两周的折腾的，终于在window下调通了，不过还有个问题，不太明白，就是在Ubuntu下测试，得到的置信度很高，检测结果也可用，但是在windows下得到的置信度很低，不明白为什么这样，
> > > ![9257a518-265e-4797-975f-3b1988e7650f](https://user-images.githubusercontent.com/32634125/50064550-c1fcf180-01ec-11e9-8f73-d7c905123d84.png)
> > > ![img_20181217_110800_ b 43ddd4b](https://user-images.githubusercontent.com/32634125/50064562-ccb78680-01ec-11e9-899f-2a280aea735d.jpg)
> > > （不知道这样能不能把图片传上去，解释一下图片）第一张图是Windows的测试结果，我打印了一下det_conf的值，基本上都是0.2-0.3之间，而且有很多。第二张图是Ubuntu下的测试结果，con_det只有两个值，而且接近1，（同一张图）。在Windows下我没有训练，就是调用Ubuntu下训练得到的模型。为什么会出现检测结果不正确这种情况。
> > > 感谢您。
> > 
> > 
> > 您好，我也遇到这样的问题，而且如果是五类的话，所有的响应值都是处在这个范围内，不知道是哪里的问题？您解决了吗？
> 
> 没有解决，你也是移植到Windows下了吗？

是的，但是响应阈值都很低，不知道什么情况

**Comment by wolfworld6** [comment]
> @chaobeiying @wolfworld6
> 不好意思，由于我没用过windows下的caffe，没遇到过类似的问题，所以也不知道是啥问题。

非常感谢您的回复，今天重新在linux下进行了测试，结果阈值依然是0.2附近，不知道问题出在哪里

**Comment by chaobeiying** [comment]
> @chaobeiying @wolfworld6
> 不好意思，由于我没用过windows下的caffe，没遇到过类似的问题，所以也不知道是啥问题。

谢谢您啦

**Comment by chaobeiying** [comment]
> @chaobeiying @wolfworld6
> 不好意思，由于我没用过windows下的caffe，没遇到过类似的问题，所以也不知道是啥问题。

再次感谢，我还想问您一个问题，前传Python接口用的是net.forward()，那么C++接口用什么啊？

**Comment by sfzhang15** [comment]
@wolfworld6 
在linux下测试，结果阈值依然是0.2附近？？

**Comment by sfzhang15** [comment]
@chaobeiying 
我大部分前传都是用的Python接口，由于c++前传不好调试和可视化，所以基本没怎么用过。

**Comment by sfzhang15** [comment]
@wolfworld6 @chaobeiying 
我的师兄在windows上跑过SSD系列代码，他是用的VS2013，然后参考的是这个[官网c++前传的例子](https://github.com/BVLC/caffe/blob/master/examples/cpp_classification/classification.cpp)，不知道是否对你们有帮助。

**Comment by wolfworld6** [comment]
谢谢，已解决


在2019年3月4日 16:03，Shifeng Zhang<notifications@github.com> 写道：

@wolfworld6@chaobeiying
我的师兄在windows上跑过SSD系列代码，他是用的VS2013，然后参考的是这个官网c++前传的例子，不知道是否对你们有帮助。

**Comment by flyfts** [comment]
> 谢谢，已解决 在2019年3月4日 16:03，Shifeng Zhang<notifications@github.com> 写道： @wolfworld6@chaobeiying 我的师兄在windows上跑过SSD系列代码，他是用的VS2013，然后参考的是这个官网c++前传的例子，不知道是否对你们有帮助。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

您好，我也碰到同样的问题，我是基于SSD-Windows上的框架进行调整修改，将模型移植到了windows上了，包括训练和测试都通过，但就是在windows上调用已训练好的模型得到的得分置信度很低，在ubuntu上很正常，直接用github上提供的模型跑出来的结果都是score在0.06-0.07之间，一直没找到问题的原因。请问您是怎么解决的？能说明下问题在哪？谢谢了！
![无标题](https://user-images.githubusercontent.com/19721660/55542680-25f2e980-56fa-11e9-95b0-741836b87ce0.png)

**Comment by sfzhang15** [comment]
@wolfworld6 
你好，不知道你是否能够帮助@flyfts 解决他的问题？

**Comment by wolfworld6** [comment]
> > 谢谢，已解决 在2019年3月4日 16:03，Shifeng Zhang[notifications@github.com](mailto:notifications@github.com) 写道： @wolfworld6@chaobeiying 我的师兄在windows上跑过SSD系列代码，他是用的VS2013，然后参考的是这个官网c++前传的例子，不知道是否对你们有帮助。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 您好，我也碰到同样的问题，我是基于SSD-Windows上的框架进行调整修改，将模型移植到了windows上了，包括训练和测试都通过，但就是在windows上调用已训练好的模型得到的得分置信度很低，在ubuntu上很正常，直接用github上提供的模型跑出来的结果都是score在0.06-0.07之间，一直没找到问题的原因。请问您是怎么解决的？能说明下问题在哪？谢谢了！
> ![无标题](https://user-images.githubusercontent.com/19721660/55542680-25f2e980-56fa-11e9-95b0-741836b87ce0.png)

您好，我的最终问题还是定位在了训练数据和anchor的问题，就是anchor没有回归到检测目标的大小，介意您看一下中间结果

**Comment by sfzhang15** [comment]
@wolfworld6 
现在大家遇到的问题是：linux训好的模型在linux上测试没有问题，把linux上训好的模型在windows上测试，结果不大对，好像是得分都比较低。你之前说的已解决，是说的上面这个问题已解决吗？

**Comment by wolfworld6** [comment]
> @wolfworld6
> 现在大家遇到的问题是：linux训好的模型在linux上测试没有问题，把linux上训好的模型在windows上测试，结果不大对，好像是得分都比较低。你之前说的已解决，是说的上面这个问题已解决吗？

是的，我之前也是这个问题，最终解决的办法就是我刚才所说的。

**Comment by sfzhang15** [comment]
@wolfworld6 
你好，刚刚你说的解决方案是"我的最终问题还是定位在了**训练数据**和anchor的问题，就是anchor没有回归到检测目标的大小"，如果只是在windows上测试linux下训好的正确的模型，为什么会涉及到训练数据问题呀？另外你说的anchor没有回归到检测目标的大小，是指前传的部分代码出问题了吗？

**Comment by wolfworld6** [comment]
> @wolfworld6
> 你好，刚刚你说的解决方案是`我的最终问题还是定位在了**训练数据**和anchor的问题，就是anchor没有回归到检测目标的大小`，如果只是在windows上测试linux下训好的正确的模型，为什么会涉及到训练数据问题呀？另外你说的anchor没有回归到检测目标的大小，是指前传的部分代码出问题了吗？

1.我开始以为我的linux结果也是正确的，是因为测试数据场景简单，但是在windows下集成在产品中测试的时候使用的现场复杂的场景，所以误认为是win和linux不一致；
2.代码没问题，我的数据集中的同一目标分布很广，不集中，源代码中回归时最优anchor大小与我数据的目标大小overlap小于0.5

**Comment by sfzhang15** [comment]
@wolfworld6 
明白了，那就是说，你那边的话，训好的一个模型，linux和windows结果是一致的。现在好几个人遇到的问题是，同一个模型，linux和windows结果对不上，应该跟你的情况不一致。

**Comment by flyfts** [comment]
thanks very much !!! @sfzhang15 @wolfworld6 @chaobeiying 这个问题总算彻底解决了，经过两天的测试找到了原因。经过对比发现，windows下加载的模型总是只复制训练好的第一层模型，也就是问题定位在了模型加载函数上了，最后定位这个函数io.cpp 的函数bool ReadProtoFromBinaryFile(const char* filename, Message* proto) 上了。在windows上默认调用的是int fd = open(filename, O_RDONLY);不是以二进制文件读取的方式读取模型文件，导致模型加载出错，改动如下：
![image](https://user-images.githubusercontent.com/19721660/56006989-a375b580-5d09-11e9-9d12-2a5bfd560f4d.png)
最终模型也正常显示结果：
![image](https://user-images.githubusercontent.com/19721660/56007145-4b8b7e80-5d0a-11e9-801a-b9cb9ee790ac.png)
再次谢谢大家，后续做进一步测试后，我会将windows移植版本上传到github。

**Comment by sfzhang15** [comment]
@flyfts 
好的，非常感谢

**Comment by zhangyunming** [comment]
> thanks very much !!! @sfzhang15 @wolfworld6 @chaobeiying 这个问题总算彻底解决了，经过两天的测试找到了原因。经过对比发现，windows下加载的模型总是只复制训练好的第一层模型，也就是问题定位在了模型加载函数上了，最后定位这个函数io.cpp 的函数bool ReadProtoFromBinaryFile(const char* filename, Message* proto) 上了。在windows上默认调用的是int fd = open(filename, O_RDONLY);不是以二进制文件读取的方式读取模型文件，导致模型加载出错，改动如下：
> ![image](https://user-images.githubusercontent.com/19721660/56006989-a375b580-5d09-11e9-9d12-2a5bfd560f4d.png)
> 最终模型也正常显示结果：
> ![image](https://user-images.githubusercontent.com/19721660/56007145-4b8b7e80-5d0a-11e9-801a-b9cb9ee790ac.png)
> 再次谢谢大家，后续做进一步测试后，我会将windows移植版本上传到github。

您好，请问，你现在将代码传到git上了吗，我也在折腾windows c++版本
