### ISSUE TITLE
数据增广的问题

### ISSUE THREAD

**Issue by CNHNLP** [sfzhang15/RefineDet#137]
您好 @sfzhang15 ，RefineDet中基本上使用了SSD的数据增广方法，但是这种增广方法的实质 有没有增加数据集样本数量？还是说数据集样本数量并没有改变，只是某个样本以一定的概率发生变化？

**Comment by CNHNLP** [comment]
感谢回答； @sfzhang15 还有一点疑问，我使用refineDet训练自己的数据集时发现在epoch=20的时候，loss只能降到7.5左右，base_lr=0.001; 您在训练的时候Loss能降到什么水平

**Comment by sfzhang15** [comment]
@CNHNLP 
你好，voc上训练最后的loss在3左右，不同的数据集可能不一样，你先测测精度怎么样，要是精度不行，可能需要调一调各个参数。

**Comment by CNHNLP** [comment]
感谢回答@sfzhang15   更改了lr的下降策略 结果好了很多；
