### ISSUE TITLE
CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by zhangbohnu** [sfzhang15/RefineDet#138]
你好   我训练的时候，遇到了这个错误。环境为cuda8.0, cudnn5.0,  同环境运行ssd没问题。
执行代码为   python examples/refinedet/VGG16_VOC2007_512.py
代码 仅仅修改了num_classes       
期待你的解答

I1210 16:49:29.264832 36607 net.cpp:150] Setting up data_data_0_split
I1210 16:49:29.264842 36607 net.cpp:157] Top shape: 8 3 512 512 (6291456)
I1210 16:49:29.264845 36607 net.cpp:157] Top shape: 8 3 512 512 (6291456)
I1210 16:49:29.264850 36607 net.cpp:157] Top shape: 8 3 512 512 (6291456)
I1210 16:49:29.264854 36607 net.cpp:157] Top shape: 8 3 512 512 (6291456)
I1210 16:49:29.264858 36607 net.cpp:157] Top shape: 8 3 512 512 (6291456)
I1210 16:49:29.264891 36607 net.cpp:165] Memory required for data: 150994976
I1210 16:49:29.264897 36607 layer_factory.hpp:77] Creating layer label_data_1_split
I1210 16:49:29.264909 36607 net.cpp:100] Creating Layer label_data_1_split
I1210 16:49:29.264915 36607 net.cpp:434] label_data_1_split <- label
I1210 16:49:29.264921 36607 net.cpp:408] label_data_1_split -> label_data_1_split_0
I1210 16:49:29.264928 36607 net.cpp:408] label_data_1_split -> label_data_1_split_1
I1210 16:49:29.264963 36607 net.cpp:150] Setting up label_data_1_split
I1210 16:49:29.264971 36607 net.cpp:157] Top shape: 1 1 1 8 (8)
I1210 16:49:29.264976 36607 net.cpp:157] Top shape: 1 1 1 8 (8)
I1210 16:49:29.264978 36607 net.cpp:165] Memory required for data: 150995040
I1210 16:49:29.264981 36607 layer_factory.hpp:77] Creating layer conv1_1
I1210 16:49:29.265002 36607 net.cpp:100] Creating Layer conv1_1
I1210 16:49:29.265008 36607 net.cpp:434] conv1_1 <- data_data_0_split_0
I1210 16:49:29.265017 36607 net.cpp:408] conv1_1 -> conv1_1
I1210 16:49:29.370558 36613 blocking_queue.cpp:50] Waiting for data
F1210 16:49:29.985205 36607 cudnn.hpp:122] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
*** Check failure stack trace: ***
    @     0x7f62582295cd  google::LogMessage::Fail()
    @     0x7f625822b433  google::LogMessage::SendToLog()
    @     0x7f625822915b  google::LogMessage::Flush()
    @     0x7f625822be1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f6258a253f8  caffe::CuDNNConvolutionLayer<>::Reshape()
    @     0x7f6258963361  caffe::Net<>::Init()
    @     0x7f6258964be1  caffe::Net<>::Net()
    @     0x7f625898b2da  caffe::Solver<>::InitTrainNet()
    @     0x7f625898c5d7  caffe::Solver<>::Init()
    @     0x7f625898c97a  caffe::Solver<>::Solver()
    @     0x7f62589a84b3  caffe::Creator_SGDSolver<>()
    @           0x40ac89  train()
    @           0x407590  main
    @     0x7f6257199830  __libc_start_main
    @           0x407db9  _start
    @              (nil)  (unknown)
Aborted

**Comment by sfzhang15** [comment]
@zhangbohnu 
你好，为什么修改了num_classes？

**Comment by zhangbohnu** [comment]
我用了自己的数据集（VOC格式）   所以改了

**Comment by sfzhang15** [comment]
@zhangbohnu 
只改了num_classes吗？有改其他什么地方吗？

**Comment by sfzhang15** [comment]
@zhangbohnu 
那奇怪了，一般这个错误，可能导致的原因是卷到后面，特征不大够大了，还下采样，就会出现，你把你那边生成的train.prototxt发个链接，我看一下。

**Comment by zhangbohnu** [comment]
`
[train.prototxt.txt](https://github.com/sfzhang15/RefineDet/files/2670884/train.prototxt.txt)

`

**Comment by sfzhang15** [comment]
@zhangbohnu 
你数据集有多少类？发给我的prototxt里是21类？

**Comment by zhangbohnu** [comment]
哦 我换成了原始的VOC数据   还是出现开始的问题

**Comment by zhangbohnu** [comment]
@sfzhang15   嗨  根据prototxt，看不出原因是吗

**Comment by zhangbohnu** [comment]
这样就可以了
engine: CAFFE
in the
convolution_param

**Comment by sfzhang15** [comment]
@zhangbohnu 
实在不好意思，这几天在外面，我看prototxt确实没看出啥问题，现在解决了就行。

**Comment by zhangbohnu** [comment]
@sfzhang15   还是很感谢！

**Comment by wait1988** [comment]
@zhangbohnu 不同engine之间有什么区别呢

**Comment by zhangbohnu** [comment]
应该是部分层的实现cudnn5.0不支持，所以加入engine: CAFFE，会用非cudnn版本运行。
升级cudnn到7.0是没有问题的。但奇怪的是：两者在速度上几乎没有差别
