### ISSUE TITLE
Installation instructions unclear

### ISSUE THREAD

**Issue by codingquark** [sfzhang15/RefineDet#14]
The 1st step of installation says:

> Get the code. We will call the directory that you cloned Caffe into `$RefineDet_ROOT`.

I am not able to understand if the sentence is to be parsed as "We will call [the directory that you cloned Caffe into] `$RefineDet_ROOT`" or that RefineDet will call the directory where caffe is installed, or that one has to clone Caffe somewhere within RefineDet's repo.

**Comment by sfzhang15** [comment]
@codingquark Hi, sorry about the installation instructions unclear. We have updated the README.md as "Get the code. We will call the cloned directory as $RefineDet_ROOT."  Do you think this is clear?

**Comment by codingquark** [comment]
Yes, I think that makes it clear. Thanks!
