### ISSUE TITLE
no module named gpu_nms or cpu_nms

### ISSUE THREAD

**Issue by Chanbluky** [sfzhang15/RefineDet#140]
Hi sfzhang,
    when i run the refinedet_test.py, i encountered the following issue:
from fast_rcnn.nms_wrapper import nms, soft_nms
  File "/home/alg/Vector/RefineDet/test/lib/fast_rcnn/nms_wrapper.py", line 9, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms

do you know how solver the problem?

**Comment by yisiyinheluojiutian** [comment]
> just tried "make" command in the lib directory, it works now.

I have tried 'make' but it doesn't work
