### ISSUE TITLE
关于min_size和aspect_ratios中的问题

### ISSUE THREAD

**Issue by wolfworld6** [sfzhang15/RefineDet#142]
老师您好，首先很高兴看到您的论文，但是现在呢遇到一个问题，现在我用您的网络训练自己的数据集，进行五类目标的检测，原图是1080p的照片，并将min_size中的尺寸给成了自己数据集中的目标大小，进行训练迭代到5万次左右，loss下降到5左右，但是进行预测的时候效果很差，您是否能告知其他地方需要修改呢？跪谢！
另外：
1.在您公开的512中，min_sizes = [32, 64, 128, 256]最大为256？那么再256之外的目标能回归吗？
2.为什么预测的响应值都处在同意范围内，比如五类的响应值都处在0.5左右附近，loss没用一样。

**Comment by sfzhang15** [comment]
@wolfworld6 
你的训练大小是多少？min_size改成了多少？
1. 第一阶段的min_sizes是 [32, 64, 128, 256]，第二阶段的anchor是经过第一阶段调整过的，所以anchor的范围变大了，比如25~400，第二阶段在此基础上继续回归，所以应该能检到20~500之间的物体
2. 这个可能跟你没改对有关系

**Comment by wolfworld6** [comment]
> @wolfworld6
> 你的训练大小是多少？min_size改成了多少？
> 
> 1. 第一阶段的min_sizes是 [32, 64, 128, 256]，第二阶段的anchor是经过第一阶段调整过的，所以anchor的范围变大了，比如25-400，第二阶段在此基础上继续回归，所以应该能检到20~500之间的物体
> 2. 这个可能跟你没改对有关系

非常感谢您在百忙之中回复，困扰了我一周了：
我的训练集有4000多张，但是图像中目标很多，按人这一类说，每一张图平均就有10个人。以下是min_sizes的值，按照SSD源码提供的代码计算： min_sizes = [[22.4,48], [48, 150.4], [150.4,252.8], [252.8,355.2]]
另外：
2.除了类别，anchor、aspect_ratios修改之后，其他地方没有需要修改的吧？如果不对min_sizes进行修改，直接用您提供的min_sizes，预测结果很糟糕

**Comment by sfzhang15** [comment]
@wolfworld6 
你好，一般利用一个算法在自己的数据集上训练，需要按照你数据集的特点，重新设计anchor铺设在哪一层，以及每一层的大小和比例。最好也要根据自己数据集的特点，调整一下数据増广。由于你的图片数量比较少，学习率和迭代次数可能也需要调。我只跟你说的，也没办法分析，希望你自己多分析分析，然后进行相应的改动。
