### ISSUE TITLE
尝试自己做一个refinedet的网络来训练数据，但是有些问题。。。

### ISSUE THREAD

**Issue by AiIsBetter** [sfzhang15/RefineDet#144]
您好，最近读了refinedet的论文和代码很多遍，想自己实现一个，现在实现和训练中遇到些问题，希望向您请教一下：
1.对于arm部分的loss，分类部分的loss是不是要考虑正负样本的loss，因为看到文章arm部分的分类loss lb中有li>=1这个表达，不是很清楚分类部分loss这个表达的意思。
2.对于odm部分，我根据对文章的理解，将arm部分的loc与原有的gtbox重新匹配生成了refine anchor，然后传入odm进行loss的计算，这部分需要过滤掉背景分类预测值>0.99的负样本，这个可以理解为直接扔掉这部分gtlabel为负样本的不计算loss就可以了吗？还是要扔掉renfine anchor里面满足这个条件的gtlabel为正负的样本了？
3.gt match这块，我直接将gtbox和所有priorbox匹配，通过iou>0.5的值不断更新更加匹配的框，一次性完成所有priorbox的最大iou的匹配，没有先找gtbox最匹配的prior，然后找prior最匹配的gtbox这种方式，这个对于匹配会有影响吗。
4.我实现的是vgg320结构的，但是我想用自己的数据直接训练，因为之前用ssd训练的效果尚可，看这个能否有提升，但是训练的时候loss基本上就是ssdloss的两倍，就是两部分loss叠加，收敛不下去了，模型用起来也并没有训练到比ssd效果更好的情况。请问这有可能是没有finetune的原因，还是实现方面的问题呢。vgg320结构可以直接用自己的数据训练吗，数据量不大。
问题有点多，也是卡了很久了。如果您有时间，希望不吝赐教，万分感谢。

**Comment by zslcodestorehouse** [comment]
感谢您的耐心回复，按照您的解释修改了代码，目前在我的数据集上模型的效果已经比ssd提升了不少，特别是框的位置准了很多，谢谢~
