### ISSUE TITLE
根据GPU的dockerfile进行安装出现错误

### ISSUE THREAD

**Issue by NogizakaDaisuki** [sfzhang15/RefineDet#146]
你好。我在docker的环境上用 RefineDet/docker/standalone/gpu里面的makefile进行build操作的时候出现了以下错误：

![default](https://user-images.githubusercontent.com/31687060/50474570-cacb9f80-0a04-11e9-8625-7040ffa43b36.JPG)

这个似乎是在pip的python 2和3版本之间发生了冲突。请问这个应该如何解决

**Comment by sfzhang15** [comment]
@NogizakaDaisuki 
你好，docker这个是另外一个contributor搞的，我帮你@一下他，看看他知道不知道怎么解决。

@fukatani 
你好，能麻烦你帮忙看一下这个问题吗？

**Comment by fukatani** [comment]
@NogizakaDaisuki @sfzhang15 
你好!
Thank you for trying docker and report the issue.
I think this behavior is related to https://stackoverflow.com/questions/49836676/error-after-upgrading-pip-cannot-import-name-main 

Edit dockerfile and
```
RUN sudo pip install --upgrade pip && \
    for req in $(cat python/requirements.txt) pydot easydict; do pip install $req; done && \
    make py -j"$(nproc)"
```
may work.
