### ISSUE TITLE
Unable to compile with `make all`, protoc error

### ISSUE THREAD

**Issue by codingquark** [sfzhang15/RefineDet#15]
Getting the following error while `make all`:

```
PROTOC src/caffe/proto/caffe.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from .build_release/src/caffe/proto/caffe.pb.cc:5:0:
.build_release/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
.build_release/src/caffe/proto/caffe.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
.build_release/src/caffe/proto/caffe.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from .build_release/src/caffe/proto/caffe.pb.cc:5:0:
.build_release/src/caffe/proto/caffe.pb.h:23:35: fatal error: google/protobuf/arena.h: No such file or directory
compilation terminated.
Makefile:582: recipe for target '.build_release/src/caffe/proto/caffe.pb.o' failed
make: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 1
```

I think it is because I have installed an incompatible version of protoc. 

I have updated my `$PYTHONPATH`.

System is running Ubuntu 16.04, GTX 1080.

**Comment by sfzhang15** [comment]
@codingquark Hi, this should be a common mistake when compiling caffe and according to the error message, this may be due to the version of protoc. We have encountered similar problems before. You can use the command 'protoc --version' and 'which protoc'  to check your protoc's version and path. You can try to find relevant solutions online to update your protoc. Hope these can be helpful to you.

**Comment by codingquark** [comment]
Thanks for the reply!

Does RefineDet need a specific version of protoc, or is it the one that is used by caffe (and hence can be investigated with caffe sources directly)?

**Comment by sfzhang15** [comment]
@codingquark We have successfully compiled the RefineDet with libprotoc 2.5.0, 2.6.1 and 3.3.2. So it should not need a specific version of protoc.
