### ISSUE TITLE
test问题

### ISSUE THREAD

**Issue by xiaoshang123** [sfzhang15/RefineDet#150]
您好，最近拜读你的论文和部分开源代码，受益良多，遇到两个问题，还请老师指教：
1. 使用python程序生成代码时，遇到问题，如下所示
Cannot copy param 0 weights from layer 'P3_mbox_conf'; shape mismatch.  Source param shape is 63 256 3 3 (145152); target param shape is 6 256 3 3 (13824). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
2.该网络模型是否适用于二分类（目标和背景），如果适用，是否只是单纯地将num_classes改为2即可
希望老师指导，非常感谢！

**Comment by xiaoshang123** [comment]
感谢老师及时回复

**Comment by xiaoshang123** [comment]
老师，我使用refinedet网络进行二分类，将labelmap_voc.prototxt改为background和person，用您预训练好的模型（VOC0712_refinedet_vgg16_512x512_final.caffemodel）进行训练，在训练迭代到1000次时出现如下问题：
*** Aborted at 1547433244 (unix time) try "date -d @1547433244" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 4732 (TID 0x7f3199669a40) from PID 0; stack trace: ***
    @     0x7f319697bcb0 (unknown)
    @                0x0 (unknown)
    @     0x7f319887bb92 caffe::Net<>::ForwardFromTo()
    @      0x3e843d31482 (unknown)
    @         0x97da7f40 (unknown)
Segmentation fault (core dumped)
但是我在使用voc数据集进行训练时就没有这个问题，还请老师解答，非常感谢！

**Comment by sfzhang15** [comment]
@xiaoshang123 
1000次的时候有在测试还是在保存模型？

**Comment by xiaoshang123** [comment]
测试模型

**Comment by sfzhang15** [comment]
@xiaoshang123 
可以先尝试make clean之后，在重新编译一下caffe，此外可以检测一下测试，看看是不是哪里有问题。

**Comment by xiaoshang123** [comment]
我根据ssd测试网络，在refinedet测试网络中添加如下代码   
save_output_param {
      output_directory: "examples/SSD_nodule/refinedet_me/results"
      output_name_prefix: "comp4_det_test_"
      output_format: "VOC"
      label_map_file: "examples/SSD_nodule/refinedet_me/labelmap_voc.prototxt"
      name_size_file: "examples/SSD_nodule/refinedet_me/test_name_size.txt"
      num_test_image: 1738
    }
测试迭代到1000次就会出现Segmentation fault (core dumped)这个问题，但是当我注释掉
      label_map_file: "examples/SSD_nodule/refinedet_me/labelmap_voc.prototxt"时网络就能够继续往下迭代，detection_eval 一直是0
我先按照您上边的方法尝试一下，谢谢！

**Comment by xiaoshang123** [comment]
老师，按照你的方法重新编译refinedet之后，检查测试网络，问题还是没有解决，依旧是迭代到1000次的时候显示如下问题：
*** Aborted at 1547526148 (unix time) try "date -d @1547526148" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 6598 (TID 0x7f3ee5d7da40) from PID 0; stack trace: ***
    @     0x7f3ee3096cb0 (unknown)
    @                0x0 (unknown)
    @     0x7f3ee4f91132 caffe::Net<>::ForwardFromTo()
    @      0x3e843f85191 (unknown)
    @         0x98732fb0 (unknown)
Segmentation fault (core dumped)
但是使用ssd进行二分类的时候没有这个问题

**Comment by sfzhang15** [comment]
@xiaoshang123 
1. 你用什么数据集在训练行人检测？
2. 测试集有1738张图？测试的batch_size是多少？
3. 你尽量自己多检查检查，我这边没有相关信息，很难定位问题出在哪。

**Comment by xiaoshang123** [comment]
1.我想用refinedet网络对医学图像进行二分类（有病变和无病变）
2.测试集1738张，batch_size设置为2
3.我想把测试结果输出来绘制曲线，所以就在test网络中添加了几行代码：
save_output_param {
output_directory: "examples/SSD_nodule/refinedet_me/results"
output_name_prefix: "comp4_det_test_"
output_format: "VOC"
label_map_file: "examples/SSD_nodule/refinedet_me/labelmap_voc.prototxt"
name_size_file: "examples/SSD_nodule/refinedet_me/test_name_size.txt"
num_test_image: 1738
}
4.对文章中的曲线分析的还不是很明白，请老师多多指点

**Comment by sfzhang15** [comment]
@xiaoshang123 
1.  只凭你提供的这么点信息，我也不知道是什么问题，你把solver.prototxt、test.prototxt、train.prototxt上传我看一下
2. 要画曲线，得改一下测试代码，只改prototxt没用的
3. ‘对文章中的曲线分析的还不是很明白’，文章中的曲线是只啥？
