### ISSUE TITLE
Some question about the multi-scale test

### ISSUE THREAD

**Issue by tjulyz** [sfzhang15/RefineDet#151]
Hi, 

Thanks for your kind share!
I have read your code about multi-scale test. What confuses me is that I am not sure how the network (e.g. VGG300/320) Can process images with different sizes (180x180, 360x360). So I think the multi-scale test procedure is like this:
Image Read (original size like 720x480) -> Image resize(use cv2.resize to multi-scales, such as 180*180, 360x360, etc.) -> input to net -> resize again (300x300) to the original trained model.
But I am not sure whether it is like this.  Or you directly input the images with multi-scale sizes to the same network trained with 300x300 input?

Thank you very much!

**Comment by tjulyz** [comment]
That meas the size of features for predicting the results in each scale is not fixed, right? such as, using 38x38, 19x19, 10x10 for prediction, now these sizes are changed according to different input scales?

Thank you very much!

**Comment by sfzhang15** [comment]
@tjulyz 
Yes. For the fully convolution network, the size of features is supposed to be changed accroding to the input size.

**Comment by tjulyz** [comment]
Got it! Thank you very much!!!
