### ISSUE TITLE
Re-produced result is not same as original paper one.

### ISSUE THREAD

**Issue by youngwanLEE** [sfzhang15/RefineDet#153]
Hi, I wondered [this training script](https://github.com/sfzhang15/RefineDet/blob/master/examples/refinedet/VGG16_VOC2007_320.py) produces the reported result and just tried to train using this script on 4GPU TITAN X server with same setting.

The result is below in which the mAP is lower than 80 mAP that is reported.

How do you think this result? Let me know what I miss. 

Thanks

![image](https://user-images.githubusercontent.com/13238578/51298128-a5abd900-1a66-11e9-986d-636b0a6078aa.png)

**Comment by sfzhang15** [comment]
@youngwanLEE 
The training has a little fluctuation due to randomness. You can set the IoU threshold as 0.3 (negative) and 0.7 (positive) in ARM to get more stable results.

**Comment by youngwanLEE** [comment]
@sfzhang15, thanks for reply. Could you notice where I correct exactly?

**Comment by sfzhang15** [comment]
@youngwanLEE 
Adding these two lines after [here](https://github.com/sfzhang15/RefineDet/blob/master/examples/refinedet/VGG16_VOC2007_320.py#L447)
```
multibox_loss_param_arm['overlap_threshold'] = 0.7
multibox_loss_param_arm['neg_overlap'] = 0.3
```

**Comment by youngwanLEE** [comment]
@sfzhang15 , Thanks:)
