### ISSUE TITLE
我用voc0712数据训练出现问题

### ISSUE THREAD

**Issue by zengjianyou** [sfzhang15/RefineDet#156]
大神您好，
我用VGG16_voc2007_512.py训练voc0712数据，出现arm_loss=nan的问题，我截屏给您看看，

![1](https://user-images.githubusercontent.com/34835647/51783539-5193a980-2176-11e9-8862-d9029997eda3.jpg)
然后在用自己的数据跑了下，refinedet-caffe也出现arm_loss类似问题，学习率也调了，但是arm_loss=nan

**Comment by sfzhang15** [comment]
@zengjianyou @NogizakaDaisuki 
我自己把代码重新下载了一遍，然后跑上述例子没有出现问题，提出这个issue的已经联系过我了，我把自己生成的lmdb发给了他，让他试试看是否还有问题。
