### ISSUE TITLE
question about dividing cells for anchors

### ISSUE THREAD

**Issue by wheemyungshin** [sfzhang15/RefineDet#157]
Thank you for your great job.
I read your paper and I have a question about it.
The paper said, "we associate n anchor boxes with each regularly divided cell on the feature map."
But there is no explanation about how the cell is divided.
I wonder that if the input resolution becomes larger, the number of cells becomes larger or the size of each cell becomes larger.
The way to divide the cells will cause effects to mAP, speed, memory.
I read your code too but I can't find the part dividing cells.

**Comment by sfzhang15** [comment]
@wheemyungshin 
The cell means 1x1 location in feature map, e.g., 4x4 feature map has 4x4 cells.
