### ISSUE TITLE
Do the blob parameter saved in file?

### ISSUE THREAD

**Issue by NogizakaDaisuki** [sfzhang15/RefineDet#158]
Thanks for checking this issue.
I am trying to use tensorRT to accelerate the inference of RefineDet.
But now I need the blob parameters for a intermidiate translation for the tensorRT engine.
So as mentioned in the title, do the blob parameters saved in file?
If not , where can I find the blob parameters ?

Looking for your reply.

**Comment by sfzhang15** [comment]
@NogizakaDaisuki 
The blob parameters are saved in the trained caffemodel.

**Comment by DHNicoles** [comment]
@NogizakaDaisuki Have you accelerated with TensorRT? I also have this need, can you help me? I am grateful.
