### ISSUE TITLE
How to inference with the trained coco model

### ISSUE THREAD

**Issue by NogizakaDaisuki** [sfzhang15/RefineDet#159]
As I mentioned in the title,
how can I inference with the trained coco model?
the train_demo.py file seems to just fit to VOC .

**Comment by sfzhang15** [comment]
@NogizakaDaisuki 
If you want to inference with the trained coco mode using refinedet_demo.py, you should modify [L80](https://github.com/sfzhang15/RefineDet/blob/master/test/refinedet_demo.py#L80), [L86-L87](https://github.com/sfzhang15/RefineDet/blob/master/test/refinedet_demo.py#L86-L87) correspondingly.
