### ISSUE TITLE
How can i train using more faster CNN like resnet10 and mobilenet?

### ISSUE THREAD

**Issue by campos537** [sfzhang15/RefineDet#160]
I liked a lot the results you had, but i want to train using this other CNN that are faster, to run on CPU

**Comment by sfzhang15** [comment]
@campos537 
You can replace [Res101](https://github.com/sfzhang15/RefineDet/blob/master/examples/refinedet/ResNet101_COCO_320.py#L408, https://github.com/sfzhang15/RefineDet/blob/master/examples/refinedet/ResNet101_COCO_320.py#L465) with new backbones and modify [L228](https://github.com/sfzhang15/RefineDet/blob/master/examples/refinedet/ResNet101_COCO_320.py#L228), [L253-L254](https://github.com/sfzhang15/RefineDet/blob/master/examples/refinedet/ResNet101_COCO_320.py#L253-L254) and [L298](https://github.com/sfzhang15/RefineDet/blob/master/examples/refinedet/ResNet101_COCO_320.py#L298) correspondingly.

**Comment by campos537** [comment]
Thanks for the help!

**Comment by wait1988** [comment]
Can you share your script to extract the pretrained COCO model of given classes? @sfzhang15

**Comment by sfzhang15** [comment]
@wait1988 
Please refer to [convert_model_320.ipynb](https://github.com/sfzhang15/RefineDet/blob/master/examples/convert_model_320.ipynb) and [convert_model_512.ipynb](https://github.com/sfzhang15/RefineDet/blob/master/examples/convert_model_512.ipynb).
