### ISSUE TITLE
Inference speed on contemporary hardware?

### ISSUE THREAD

**Issue by nirbenz** [sfzhang15/RefineDet#162]
Thanks for this repo and paper!
Published results are (to my understanding) performed on Titan X (Maxwell?) hardware. I'm wondering if subsequent tests were performed on more up-to-date hardware (Pascal/Volta/Turing-based).

Thanks!

**Comment by sfzhang15** [comment]
@nirbenz 
We measured the speed of RefineDet on Titan Xp, the speed was 1.5x+ faster. Because we do not have Volta/Turing-based machines and can not perform on these up-to-date hardwares.

**Comment by nirbenz** [comment]
That's pretty cool. I'd imagine FP16 could accelerate this further with no loss of accuracy but I'm not sure if Caffe supports it.

**Comment by nirbenz** [comment]
Thanks a lot!
