### ISSUE TITLE
您好,关于mAP的测试问题

### ISSUE THREAD

**Issue by lillyro** [sfzhang15/RefineDet#163]
使用别的数据集如VOC,cityperson没有问题.但是使用BDD进行测试时会报错

Traceback (most recent call last):
  File "./test/refinedet_test.py", line 60, in <module>
    single_scale_test_net(net, imdb, targe_size=input_size)
  File "/home/lilly/loli/RefineDet/test/lib/fast_rcnn/test.py", line 247, in single_scale_test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/lilly/loli/RefineDet/test/lib/datasets/pascal_voc.py", line 330, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/lilly/loli/RefineDet/test/lib/datasets/pascal_voc.py", line 299, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/home/lilly/loli/RefineDet/test/lib/datasets/voc_eval.py", line 109, in voc_eval
    recs[imagename] = parse_rec(annopath.format(imagename))
  File "/home/lilly/loli/RefineDet/test/lib/datasets/voc_eval.py", line 21, in parse_rec
    obj_struct['difficult'] = int(obj.find('difficult').text)
AttributeError: 'NoneType' object has no attribute 'text'

想问下为什么会出现这种情况呢?谢谢!

**Comment by lillyro** [comment]
已解决.打扰了不好意思

**Comment by china56321** [comment]
> 使用别的数据集如VOC,cityperson没有问题.但是使用BDD进行测试时会报错
> 
> Traceback (most recent call last):
> File "./test/refinedet_test.py", line 60, in
> single_scale_test_net(net, imdb, targe_size=input_size)
> File "/home/lilly/loli/RefineDet/test/lib/fast_rcnn/test.py", line 247, in single_scale_test_net
> imdb.evaluate_detections(all_boxes, output_dir)
> File "/home/lilly/loli/RefineDet/test/lib/datasets/pascal_voc.py", line 330, in evaluate_detections
> self._do_python_eval(output_dir)
> File "/home/lilly/loli/RefineDet/test/lib/datasets/pascal_voc.py", line 299, in _do_python_eval
> use_07_metric=use_07_metric)
> File "/home/lilly/loli/RefineDet/test/lib/datasets/voc_eval.py", line 109, in voc_eval
> recs[imagename] = parse_rec(annopath.format(imagename))
> File "/home/lilly/loli/RefineDet/test/lib/datasets/voc_eval.py", line 21, in parse_rec
> obj_struct['difficult'] = int(obj.find('difficult').text)
> AttributeError: 'NoneType' object has no attribute 'text'
> 
> 想问下为什么会出现这种情况呢?谢谢!
请问计算MAP时，refinedet_test,py里的test_set,voc_path,coco_path分别代表什么路径？可以细说一点吗？

**Comment by china56321** [comment]
> 使用别的数据集如VOC,cityperson没有问题.但是使用BDD进行测试时会报错
> 
> Traceback (most recent call last):
> File "./test/refinedet_test.py", line 60, in
> single_scale_test_net(net, imdb, targe_size=input_size)
> File "/home/lilly/loli/RefineDet/test/lib/fast_rcnn/test.py", line 247, in single_scale_test_net
> imdb.evaluate_detections(all_boxes, output_dir)
> File "/home/lilly/loli/RefineDet/test/lib/datasets/pascal_voc.py", line 330, in evaluate_detections
> self._do_python_eval(output_dir)
> File "/home/lilly/loli/RefineDet/test/lib/datasets/pascal_voc.py", line 299, in _do_python_eval
> use_07_metric=use_07_metric)
> File "/home/lilly/loli/RefineDet/test/lib/datasets/voc_eval.py", line 109, in voc_eval
> recs[imagename] = parse_rec(annopath.format(imagename))
> File "/home/lilly/loli/RefineDet/test/lib/datasets/voc_eval.py", line 21, in parse_rec
> obj_struct['difficult'] = int(obj.find('difficult').text)
> AttributeError: 'NoneType' object has no attribute 'text'
> 
> 想问下为什么会出现这种情况呢?谢谢!

想问下为什么会出现这种情况呢?谢谢!
请问计算MAP时，refinedet_test,py里的test_set,voc_path,coco_path分别代表什么路径？可以细说一点吗？我输出的全是星号#############################################################################

**Comment by china56321** [comment]
> 使用别的数据集如VOC,cityperson没有问题.但是使用BDD进行测试时会报错
> 
> Traceback (most recent call last):
> File "./test/refinedet_test.py", line 60, in
> single_scale_test_net(net, imdb, targe_size=input_size)
> File "/home/lilly/loli/RefineDet/test/lib/fast_rcnn/test.py", line 247, in single_scale_test_net
> imdb.evaluate_detections(all_boxes, output_dir)
> File "/home/lilly/loli/RefineDet/test/lib/datasets/pascal_voc.py", line 330, in evaluate_detections
> self._do_python_eval(output_dir)
> File "/home/lilly/loli/RefineDet/test/lib/datasets/pascal_voc.py", line 299, in _do_python_eval
> use_07_metric=use_07_metric)
> File "/home/lilly/loli/RefineDet/test/lib/datasets/voc_eval.py", line 109, in voc_eval
> recs[imagename] = parse_rec(annopath.format(imagename))
> File "/home/lilly/loli/RefineDet/test/lib/datasets/voc_eval.py", line 21, in parse_rec
> obj_struct['difficult'] = int(obj.find('difficult').text)
> AttributeError: 'NoneType' object has no attribute 'text'
> 
> 想问下为什么会出现这种情况呢?谢谢!

请问测试MAP时，refinedet_test.py里的test_set ,   voc_path ,coco_path应该怎么写？voc_path代表VOC的路径？coco_path代表COCO的测试集的路径吗？那test_set应该怎么写？可以细说一下吗？

**Comment by china56321** [comment]
> 已解决.打扰了不好意思
＠lillyro 请问您是怎么解决的？我也遇到了同样的问题？
