### ISSUE TITLE
Error encountered when training my own dataset

### ISSUE THREAD

**Issue by klyuan1** [sfzhang15/RefineDet#164]
Hi, Thanks for your great work!
When I was training my own data set, error happened. I only changed resize_width and resize_height in examples/refinedet/VGG16_VOC2007_512.py. Could you help? Thanks!

I0228 21:20:20.339459  8428 net.cpp:150] Setting up TL5_1_relu
I0228 21:20:20.339467  8428 net.cpp:157] Top shape: 8 256 30 45 (2764800)
I0228 21:20:20.339481  8428 net.cpp:165] Memory required for data: 27419814240
I0228 21:20:20.339484  8428 layer_factory.hpp:77] Creating layer TL5_2
I0228 21:20:20.339509  8428 net.cpp:100] Creating Layer TL5_2
I0228 21:20:20.339512  8428 net.cpp:434] TL5_2 <- TL5_1
I0228 21:20:20.339519  8428 net.cpp:408] TL5_2 -> TL5_2
I0228 21:20:20.344029  8428 net.cpp:150] Setting up TL5_2
I0228 21:20:20.344056  8428 net.cpp:157] Top shape: 8 256 30 45 (2764800)
I0228 21:20:20.344060  8428 net.cpp:165] Memory required for data: 27430873440
I0228 21:20:20.344066  8428 layer_factory.hpp:77] Creating layer P6-up
I0228 21:20:20.344075  8428 net.cpp:100] Creating Layer P6-up
I0228 21:20:20.344080  8428 net.cpp:434] P6-up <- P6_P6_relu_0_split_0
I0228 21:20:20.344086  8428 net.cpp:408] P6-up -> P6-up
I0228 21:20:20.347196  8428 net.cpp:150] Setting up P6-up
I0228 21:20:20.347208  8428 net.cpp:157] Top shape: 8 256 30 46 (2826240)
I0228 21:20:20.347213  8428 net.cpp:165] Memory required for data: 27442178400
I0228 21:20:20.347218  8428 layer_factory.hpp:77] Creating layer Elt5
I0228 21:20:20.347224  8428 net.cpp:100] Creating Layer Elt5
I0228 21:20:20.347227  8428 net.cpp:434] Elt5 <- TL5_2
I0228 21:20:20.347232  8428 net.cpp:434] Elt5 <- P6-up
I0228 21:20:20.347277  8428 net.cpp:408] Elt5 -> Elt5
F0228 21:20:20.347643  8428 eltwise_layer.cpp:34] Check failed: bottom[i]->shape() == bottom[0]->shape() 
*** Check failure stack trace: ***
    @     0x7f662662edaa  (unknown)
    @     0x7f662662ece4  (unknown)
    @     0x7f662662e6e6  (unknown)
    @     0x7f6626631687  (unknown)
    @     0x7f6626d85d3d  caffe::EltwiseLayer<>::Reshape()
    @     0x7f6626eb8f17  caffe::Net<>::Init()
    @     0x7f6626eb9d55  caffe::Net<>::Net()
    @     0x7f6626ce7bd2  caffe::Solver<>::InitTrainNet()
    @     0x7f6626ce812c  caffe::Solver<>::Init()
    @     0x7f6626ce843a  caffe::Solver<>::Solver()
    @     0x7f6626ece9a3  caffe::Creator_SGDSolver<>()
    @           0x40db27  caffe::SolverRegistry<>::CreateSolver()
    @           0x408df9  train()
    @           0x40671c  main
    @     0x7f6624ceff45  (unknown)
    @           0x407023  (unknown)
    @              (nil)  (unknown)

**Comment by sfzhang15** [comment]
@klyuan1 
Hi, the input size should be a multiple of 64. If you want to imput any size, you should add crop_layer before eltwise_layer to keep the input sizes of both equal.

**Comment by klyuan1** [comment]
@sfzhang15
Big thanks to you! It's really help me!

**Comment by china56321** [comment]
> @klyuan1
> Hi, the input size should be a multiple of 64. If you want to input any size, you should add crop_layer before eltwise_layer to keep the input sizes of both equal.

> @sfzhang15
Could you tell me how you add the crop_layer?  Really appreciated!

**Comment by sfzhang15** [comment]
@china56321 
Please refer to [this](https://blog.csdn.net/Sunshine_in_Moon/article/details/52900338)
