### ISSUE TITLE
anchor setting

### ISSUE THREAD

**Issue by wait1988** [sfzhang15/RefineDet#165]
I noticed that each prediction layer has 3 anchors with the same aspect ratio,so is it enough for the task like person detection with various poses?And,how you choose the min_size and aspect ratio for each feature layer?

**Comment by sfzhang15** [comment]
@wait1988 
Each prediction layer has 3 anchors with one scales and three aspect ratios. If you detect persons, you can change the anchor setting according to your dataset. In general, we choose the min_size as about 4 times of the stride size of the prediction layer. As for aspect ratio, we choose it according to the dataset.

**Comment by wait1988** [comment]
@sfzhang15 Got it.You're so nice.
