### ISSUE TITLE
Training with negative images

### ISSUE THREAD

**Issue by nerius59** [sfzhang15/RefineDet#167]
Hi, thank you for your great job and repo!

I want to know it is possible to work with negative images(images without a true object = images that have no ground truth in its xml file) for training RefineDet.

In order to reduce false-positive detections, I added negative images to my dataset. But it seems that the negative images didn't affect the training result.

I already understand it doesn't work in SSD-caffe without modifying. (like here https://github.com/weiliu89/caffe/issues/146 , and here https://github.com/weiliu89/caffe/issues/145)

It is same for your Refindet?
Do you have any good ideas for this matter?
Thanks.

**Comment by sfzhang15** [comment]
@nerius59 
Yes, Refinedet has the same problem as SSD, since our codes are based on SSD. Training with negative images dose not work without modifying, you can refer to SSD issues to modify some codes to support.

**Comment by nerius59** [comment]
Thanks.
I'll try to modify the code.
