### ISSUE TITLE
slow speed of multi-scale testing 

### ISSUE THREAD

**Issue by ZhiweiYan-96** [sfzhang15/RefineDet#168]
Hi. Recently i try multi-scale testing code provided in this repository. However, I found that the multi-scale testing is pretty time-consuming especially when testing the COCO dataset. Could please tell me whether this situation is normal? Is there anyway to accelerate testing speed? Thank you, very much!

**Comment by sfzhang15** [comment]
@14zwyan 
You can first try the single-scale testing to check whether the speed is normal. Usually, the multi-scale testing takes several times (x10~20) more time than the single-scale testing, since the multi-scale testing uses more large scales with flipping.

**Comment by QianXin1992** [comment]
Will you willing to provide the video-test script of RefineDet?

**Comment by sfzhang15** [comment]
@QianXin1992 
Sorry, we do not have the test script for video, maybe you can extract images from video and then test these extracted images.
