### ISSUE TITLE
multi_scale test.....

### ISSUE THREAD

**Issue by AiIsBetter** [sfzhang15/RefineDet#169]
Hi@sfzhang15
I didn't configure the environment for caffe, so I just looked at the code. In refine_test, input non-size pictures to net for detection, and then do some post-processing. But isn't a trained model that can only predict fixed-size images? So how does this work? Looking forward to your response.

**Comment by sfzhang15** [comment]
@AiIsBetter 
RefineDet is a fully convolutional network, so it can has any size of input images. For single-cale testing, the testing input size should be the same as the training input size to have best performance. For multi-scale testing, we can use many scales to test the model and then merge these results.

**Comment by AiIsBetter** [comment]
I understand. I've tried it myself. That's it. Thank you.

**Comment by AiIsBetter** [comment]
> @AiIsBetter
> RefineDet is a fully convolutional network, so it can has any size of input images. For single-cale testing, the testing input size should be the same as the training input size to have best performance. For multi-scale testing, we can use many scales to test the model and then merge these results.

I understand. I've tried it myself. That's it. Thank you.
