### ISSUE TITLE
how to measure fps?

### ISSUE THREAD

**Issue by youngwanLEE** [sfzhang15/RefineDet#17]
Hi, 

How to measure the inference speed?

To  my knowledge, SSD's author measured the fps by train log file that showed train loss and evaluated results.

**Comment by sfzhang15** [comment]
@youngwanLEE Hi
We measure the inference speed via the 'time' model of caffe with batch_size = 1.

**Comment by youngwanLEE** [comment]
@sfzhang15, Thanks for your reply.

You mean 'caffe time' function?

**Comment by sfzhang15** [comment]
@youngwanLEE Yes

**Comment by youngwanLEE** [comment]
@sfzhang15 
I got this error when trying to test using this command,

`build/tools/caffe time -model=models/VGGNet/VOC0712/refinedet_vgg16_320x320/test.prototxt -weights=models/VGGNet/VOC0712/refinedet_vgg16_320x320/VOC0712_refinedet_vgg16_320x320_final.caffemodel -gpu=0
`

> F1218 14:32:07.013154 32394 insert_splits.cpp:29] Unknown bottom blob 'data' (layer 'conv1_1', bottom index 0)
*** Check failure stack trace: ***
    @     0x7f601c3c9daa  (unknown)
    @     0x7f601c3c9ce4  (unknown)
    @     0x7f601c3c96e6  (unknown)
    @     0x7f601c3cc687  (unknown)
    @     0x7f601cb4565c  caffe::InsertSplits()
    @     0x7f601cac23da  caffe::Net<>::Init()
    @     0x7f601cac5a43  caffe::Net<>::Net()
    @           0x40b1c7  time()
    @           0x406728  main
    @     0x7f601ac10f45  (unknown)
    @           0x406f8c  (unknown)
    @              (nil)  (unknown)


Could you advice what I missing?

**Comment by sfzhang15** [comment]
@youngwanLEE 
build/tools/caffe time -model=models/VGGNet/VOC0712/refinedet_vgg16_320x320/deploy.prototxt -gpu=0

**Comment by foralliance** [comment]
@sfzhang15 
when compute FPS, need set batch_size=1. how and where to set??
is the first dim in the "input shape" in "deploy.prototxt"??

input_shape {
  dim: 1  # this one??
  dim: 3
  dim: 320
  dim: 320
}

**Comment by foralliance** [comment]
@sfzhang15 
when compute FPS, need set batch_size=1. how and where to set??
is the first dim in the "input shape" in "deploy.prototxt"??

input_shape {
dim: 1 # this one??
dim: 3
dim: 320
dim: 320
}

If not this, where to change?

**Comment by sfzhang15** [comment]
@foralliance Yes, it is. If you want to set batch_size = N, you just modify it to N.

**Comment by foralliance** [comment]
@sfzhang15 
many thanks

another question. for some other algorithms, like Faster R-CNN, how to compute FPS??
Is that according to the information in the log：im_detect: 4938/4952 0.066s 0.001s??

If not this, how to compute??

**Comment by sfzhang15** [comment]
@foralliance 
Because Faster R-CNN has some python layers, it can not be computer FPS via caffe time. I think the way to computer the FPS of Faster R-CNN is like what you have said.
