### ISSUE TITLE
NameError: global name 'DeconvBNLayer' is not defined

### ISSUE THREAD

**Issue by Luomoxinyan** [sfzhang15/RefineDet#170]
Hi! When I run "python examples/refinedet/ResNet101_COCO_320.py" ,I got "NameError: global name 'DeconvBNLayer' is not defined", why? Thank you!

**Comment by sfzhang15** [comment]
@Luomoxinyan 
You can modify the `sys.path.append(path)` as `sys.path.insert(0,path)` in examples/refinedet/ResNet101_COCO_320.py.
