### ISSUE TITLE
Why remove easy negative of ARM in training ODM?

### ISSUE THREAD

**Issue by Edwardmark** [sfzhang15/RefineDet#172]
Why remove easy negative of ARM in training ODM?
The easy negatives with neg_conf>=0.99 can be easily filtered in OHEM, so why bothered to remove them before OHEM in ODM training? Confused about why refineDet can deal with class imbalance, is it the job od OHEM?

**Comment by sfzhang15** [comment]
@Edwardmark 
Good question. As you have said, the easy negatives with neg_conf>=0.99 in ARM can be easily filtered by OHEM in ODM. Actually, most of the easy negatives in ARM can be filtered by OHEM in ODM, but still has a few negatives that are easy in ARM but hard in ODM. This is the reason why the two-step classification only has 0.5 mAP improvement. We believe that using the focal loss to replace the OHEM loss can make the two-step classification more useful.

**Comment by Edwardmark** [comment]
@sfzhang15 Thank you very much, I understand that now.

**Comment by ujsyehao** [comment]
@Edwardmark You can refer to Selective Refinement network, refindet + focal loss.
