### ISSUE TITLE
ImportError: No module named gpu_nms

### ISSUE THREAD

**Issue by yisiyinheluojiutian** [sfzhang15/RefineDet#173]
when I run python test/refinedet_test.py ,there is an error:
Traceback (most recent call last):
  File "test/refinedet_test.py", line 2, in <module>
    from fast_rcnn.test import single_scale_test_net, multi_scale_test_net_320, multi_scale_test_net_512
  File "/RefineDet/test/lib/fast_rcnn/test.py", line 5, in <module>
    from fast_rcnn.nms_wrapper import nms, soft_nms
  File "/RefineDet/test/lib/fast_rcnn/nms_wrapper.py", line 9, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms
I don't know what is the reason

**Comment by yisiyinheluojiutian** [comment]
and when i comment 'from fast_rcnn.nms_wrapper import nms, soft_nms' in the nms_wrapper.py,
Another problem occurs:
'ImportError: No module named cpu_nms'

**Comment by yisiyinheluojiutian** [comment]
i have solved the problem,thank you~

**Comment by Ekko1992** [comment]
@yisiyinheluojiutian  I just met the same issue, how did you solve it, could you share your solution plz?

**Comment by Ekko1992** [comment]
> @yisiyinheluojiutian I just met the same issue, how did you solve it, could you share your solution plz?

Okay, never mind, I just tried the solution post by others and make in 'test/lib' solved the problem.
