### ISSUE TITLE
How can I change the scale setting?

### ISSUE THREAD

**Issue by pyupcgithub** [sfzhang15/RefineDet#175]
In the orginal paper, the scale is the 4 times of the total stride size of the corresponding layer,
if i want the try more than one scale, where should i change the code ?

what the use of min_sizes and max_sizes  ?

**Comment by pyupcgithub** [comment]
@sfzhang15

**Comment by sfzhang15** [comment]
@pyupcgithub 
You can change the min_sizes to use more scales. The min_sizes will use all aspect ratios, while the max_sizes means using the sqrt(min_size * max_size) scale with only use 1:1 aspect ratio.

**Comment by pyupcgithub** [comment]
thanks for your reply.
