### ISSUE TITLE
on my own dataset, the performance of RefineDet is similar to SSD.

### ISSUE THREAD

**Issue by ZhiqiJiang** [sfzhang15/RefineDet#176]
My task have 4 classes(i.e. 客车,小车,货车,其他).

examples:
![byw_20180702164410_3](https://user-images.githubusercontent.com/29110881/58623671-17dbd680-8301-11e9-8bd3-78ce22d0a7a1.jpg)
![byw_20180702164415_4](https://user-images.githubusercontent.com/29110881/58623672-17dbd680-8301-11e9-86f5-b0560e64972f.jpg)
![byw_20180702164423_6](https://user-images.githubusercontent.com/29110881/58623673-17dbd680-8301-11e9-83a9-4722e62ff309.jpg)
![byw_20180702164106_3](https://user-images.githubusercontent.com/29110881/58623670-17434000-8301-11e9-9d44-ee19251fa505.jpg)

the training log of SSD: [VGG_VOC0712_SSD_300x300.log](https://github.com/sfzhang15/RefineDet/files/3236348/VGG_VOC0712_SSD_300x300.log)
the training log of RefineDet:  [VOC0712_refinedet_vgg16_320x320.log](https://github.com/sfzhang15/RefineDet/files/3236349/VOC0712_refinedet_vgg16_320x320.log)

**Comment by sfzhang15** [comment]
@0801130205 
You can try to modify some hyper-parameters according to your dataset.
