### ISSUE TITLE
请问推理时的图片尺寸能和训练时不一样吗

### ISSUE THREAD

**Issue by evercherish** [sfzhang15/RefineDet#177]
您好，感谢您的研究和分享！有个问题想请教一下。
我在尝试训练512尺寸的resnet-refinedet模型，但是发现训练时显存占用特别高，我只有1块1080ti的显卡，batchsize只能设为2 TAT。
我觉得小batch肯定会影响最终的训练性能，所以想着能不能先训练300的resnet-refinedet，训练好后推理时再把deploy里面的尺寸改成512。
不是很清楚这种做法有没有效果，或者它与真正以512训练出来的模型性能差多少？求大神解惑

**Comment by sfzhang15** [comment]
@evercherish 
可以不一样的，不过效果应该会下降，我们提供了训练好的320和512的模型，你可以试一下具体差多少。
