### ISSUE TITLE
显存不够

### ISSUE THREAD

**Issue by jwnirvana** [sfzhang15/RefineDet#179]
大佬，由于资源受限，请问我只有一张２０８０ｔｉ（１１Ｇ）能转这个代码吗？还有一个问题就是，看过你在前沿学生论坛的分享，只有一张卡对于检测这个方向想发论文有什么建议，比如是不是不能从头训练，需要借助ｉｍａｇｅｎｅｔ预训练模型，是不是最好做ｏｎｅｓ－ｔａｇｅ的等等？

**Comment by sfzhang15** [comment]
@jwnirvana 
1. 只有1张11G卡的话，应该只能跑320x320-vgg16的模型，512x512或者resnet101可能跑不了
2. 我个人目前也想不到只有1张卡做什么合适，感觉做啥都有些吃力，检测相关的都挺吃计算资源的
