### ISSUE TITLE
Questions about multi-scale test

### ISSUE THREAD

**Issue by WangTianYuan** [sfzhang15/RefineDet#180]
Hello, I've tried your multi-scale test code, but I have some questions:
I test the single-scale test on M2Det, it can achieve the original mAP:34.6. But when I use 1 and 1.2x scale, I only got 31.0 mAP. In this case, I've chage the pribox config for 1.2x scale, so why I got less mAP?
the result is:
![image](https://user-images.githubusercontent.com/18389777/62195034-b0e4a780-b3ad-11e9-8d29-b9cc40c1549e.png)
![image](https://user-images.githubusercontent.com/18389777/62195047-b6da8880-b3ad-11e9-973c-37f0fbf45dae.png)

**Comment by sfzhang15** [comment]
@WangTianYuan 
What does "chage the pribox config for 1.2x scale" mean?

**Comment by WangTianYuan** [comment]
@sfzhang15 
Sorry, it's prior_box, for input size 320, the default config is
![image](https://user-images.githubusercontent.com/18389777/62595851-8d23e300-b912-11e9-8489-fde52a2547de.png)
so for 1.2x scale test, I have to change it like this:
![image](https://user-images.githubusercontent.com/18389777/62595880-b0e72900-b912-11e9-9c38-4d917c37f171.png)
Is this correct? I find that min_sizes and steps effect the result

**Comment by sfzhang15** [comment]
@WangTianYuan 
The priorbox must not be modified during the multi-scale testing.

**Comment by WangTianYuan** [comment]
@sfzhang15 
But for orginal scale 320, the feature map is [40, 20, 10, 5, 3, 1].
for 1.2 x scale, the feature map should be [48, 24, 12, 6, 3, 1]if we still use the default config, this exception will appear:
The size of tensor a (100354) must match the size of tensor b (32756) at non-singleton dimension 0

**Comment by sfzhang15** [comment]
@WangTianYuan 
The steps, min_sizes, max_sizes must not be modified during the multi-scale testing.
