### ISSUE TITLE
关于多尺度训练

### ISSUE THREAD

**Issue by china56321** [sfzhang15/RefineDet#183]
请问训练时默认就是多尺度吗？还需要额外的设置参数吗？请问下你用refinedet训练VOC或COCO用了多长时间？我用refinedet训练自己的数据集（将近3万图片），若用VGG16，几个小时就跑完了，若用RESNET101一天就跑完了。之前用YOLO系列跑，都得几天。请问这与多尺度训练有关吗？

**Comment by sfzhang15** [comment]
@china56321 
多尺度是默认打开的，SSD里面的crop和expand就是动态多尺度训练。

**Comment by CThuw** [comment]
@sfzhang15 
请问在PASCAL VOC上训练的脚本VGG16_VOC2007/2012_320/512.py都默认是多尺度的吗？我用VGG16_VOC2007_512.py训练自己的数据，图像是1080P的，一天只能迭代几千次，可以通过事先将图像缩放到512×512然后进行训练吗？

**Comment by sfzhang15** [comment]
@CThuw 
训练是动态多尺度的，通过crop、expand和resize实现。如果没修改代码的话，无论输入图像是多大，VGG16_320/512训练大小都是320x320和512x512。

**Comment by CThuw** [comment]
@sfzhang15 
我理解的动态多尺度训练是首先将每一张输入图像进行一种随机的尺度变换（crop、expand或resize），然后进行训练。这样的话输入分辨率（例如VGG16_VOC2007_512.py的输入分辨率是512×512）是不是没有意义？还是说动态多尺度的不同尺度是在输入分辨率的基础上确定的（例如通过将输入分辨率和预先设定好的不同的缩放系数相乘，从而确定一系列不同的尺度）？

**Comment by XHuaSheng** [comment]
请问使用的是啥配置的机器进行的训练呢

**Comment by sfzhang15** [comment]
@XHuaSheng 
当时使用的是4卡Titan X
