### ISSUE TITLE
bash ./data/VOC0712/create_data.sh

### ISSUE THREAD

**Issue by biexiangduo** [sfzhang15/RefineDet#184]
my datasets is in: /home/pf/data/VOCtest_06-Nov-2007.tar
/home/pf/data/VOCtrainval_06-Nov-2007.tar
/home/pf/data/VOCtrainval_11-May-2012.tar
-----------------
my project directory is in : /home/pf/RefineDet (also the same as ~/RefineDet)

when i command : bash ./data/VOC0712/create_data.sh
error as following
          
(base) pf@pf-System-Product-Name:~/RefineDet$ bash ./data/VOC0712/create_data.sh  File "/home/pf/RefineDet/data/VOC0712/../../scripts/create_annoset.py", line 76
    print "root directory: {} does not exist".format(root_dir)
                                            ^
SyntaxError: invalid syntax
  File "/home/pf/RefineDet/data/VOC0712/../../scripts/create_annoset.py", line 76
    print "root directory: {} does not exist".format(root_dir)
                                            ^
SyntaxError: invalid syntax

I can not figure the data directory and project directory. And I am not able to understand the shell 
could you help me?

**Comment by JimReno** [comment]
`root_dir` means The root directory which contains the images and annotations. There many ways to fix this issue. You can add one statement at line 73 in `create_annoset.py`: `root_dir = /home/pf/data/`. Remember to set your data path correctly. Or you can specific arg ` root` in the `create_data.sh` file in line 24
