### ISSUE TITLE
帮忙看下detection_out层输出结果不正常

### ISSUE THREAD

**Issue by taotaoyuhust** [sfzhang15/RefineDet#186]
代码如下：
############################################
 Net<float> caffe_net("F:/caffe/RefineDet-master/models/models_VGGNet_VOC0712_refinedet_vgg16_320x320/deploy.prototxt", caffe::TEST, 0); 
  caffe_net.CopyTrainedLayersFrom("F:/caffe/RefineDet-master/models/models_VGGNet_VOC0712_refinedet_vgg16_320x320/VOC0712_refinedet_vgg16_320x320_final.caffemodel"); 
 

 // 针对单张图片的

  //获取输入层尺寸 
  Blob<float>* input_layer = caffe_net.input_blobs()[0]; 

  int num_channels_ = input_layer->channels();
  CHECK(num_channels_ == 3 || num_channels_ == 1)
	  << "Input layer should have 1 or 3 channels.";
  cv::Size input_geometry_ = cv::Size(input_layer->width(), input_layer->height());

  std::cout << "num_channels_." << num_channels_;
  //打开图像
  cv::Mat imgorin = cv::imread("F:/caffe/RefineDet-master/examples/images/000456.jpg", -1);
  CHECK(!imgorin.empty()) << "Unable to decode image " << FLAGS_jpgfile;
  double t1 = (double)cv::getTickCount();
   

 
  //将输入图像reshape到输入层大小
  int width = input_layer->width();
  int height = input_layer->height();
  float* input_data = input_layer->mutable_cpu_data();
  std::vector<cv::Mat> input_channels;;
  
  std::cout << "width." << width << "height" << height;
  for (int i = 0; i < input_layer->channels(); ++i) 
  {
	  cv::Mat channel(height, width, CV_32FC1, input_data);
	  input_channels.push_back(channel);
	  input_data += width * height;
  }

  cv::Mat sample_resized;
  if (imgorin.size() != input_geometry_)
	  cv::resize(imgorin, sample_resized, input_geometry_);
  else
	  sample_resized = imgorin;
  cv::Mat sample_float;
  if (num_channels_ == 3)
	  sample_resized.convertTo(sample_float, CV_32FC3);
  else
	  sample_resized.convertTo(sample_float, CV_32FC1);

  cv::Mat sample_normalized;
  std::vector<cv::Mat> mean_channels;
  vector<float> values;
  values.push_back(104.0);
  values.push_back(117.0);
  values.push_back(123.0);
  for (int i = 0; i < num_channels_; ++i) 
  { 
	  cv::Mat channel(input_geometry_.height, input_geometry_.width, CV_32FC1, cv::Scalar(values[i]));
	  mean_channels.push_back(channel);
  }
  cv::Mat mean_;
  cv::merge(mean_channels, mean_);
  cv::subtract(sample_float, mean_, sample_normalized);

  cv::split(sample_normalized, input_channels);
   
  LOG(INFO) << "before Forward.";

  //前向传播
  caffe_net.Forward();

  LOG(INFO) << "after Forward.";

  //获取检测结果 
  std::vector<Blob<float> *>  outblobvec = caffe_net.output_blobs();
  std::vector<int> indexsss = caffe_net.output_blob_indices();
  Blob<float>* result_blob = caffe_net.output_blobs()[0];
  const float* result = result_blob->cpu_data();
  const int num_det = result_blob->height();
  vector<vector<float> > detections;
  for (int k = 0; k < num_det; ++k) 
  {
	  if (result[0] == -1) 
	  {
		  result += 7;
		  continue;
	  }
	  vector<float> detection(result, result + 7);
	  detections.push_back(detection);
	  result += 7;
  }  
  int t2 = ((double)cv::getTickCount() - t1) * 1000 / cv::getTickFrequency(); //获得时间，单位是秒
  std::cout << "time is  " << t2 << std::endl;;

  for (int i = 0; i < detections.size(); ++i) 
  {
	  const vector<float>& d = detections[i];
	  // Detection format: [image_id, label, score, xmin, ymin, xmax, ymax].
	  CHECK_EQ(d.size(), 7);
	  const float score = d[2];
	  if (score >= 0.3) 
	  {
		  std::cout << FLAGS_jpgfile << " ";
		  std::cout << static_cast<int>(d[1]) << " ";
		  std::cout << score << " ";
		  std::cout << static_cast<int>(d[3] * sample_resized.cols) << " ";
		  std::cout << static_cast<int>(d[4] * sample_resized.rows) << " ";
		  std::cout << static_cast<int>(d[5] * sample_resized.cols) << " ";
		  std::cout << static_cast<int>(d[6] * sample_resized.rows) << std::endl;
		  //show rect
		  cv::Point pt1, pt2;
		  pt1.x = sample_resized.cols*d[3];
		  pt1.y = sample_resized.rows*d[4];
		  pt2.x = sample_resized.cols*d[5];
		  pt2.y = sample_resized.rows*d[6];
		  cv::rectangle(sample_resized, pt1, pt2, cvScalar(0, 255, 0), 1, 8, 0);
	  }
  }
  std::string file1 = FLAGS_jpgfile + "_result.jpg";
  cv::imwrite(file1, sample_resized);
  cv::imshow("Show", sample_resized);
  cv::waitKey(0);

##################################################
输出结果见附件
感觉detection_out层没起作用？nms都没做一样？
帮忙看看，非常感谢！

**Comment by taotaoyuhust** [comment]
![QQ截图20190910103656](https://user-images.githubusercontent.com/18323333/64580097-b4f5e300-d3b7-11e9-8737-eabaebb8497d.jpg)

**Comment by sfzhang15** [comment]
@taotaoyuhust 
C++的前传请参考[这个](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_detect.cpp).

**Comment by taotaoyuhust** [comment]
> @taotaoyuhust
> C++的前传请参考[这个](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_detect.cpp).

是的，我就是参考这个的。。

**Comment by sfzhang15** [comment]
@taotaoyuhust 
我这边看你贴的代码看不出啥来，麻烦你自己单步调试一下吧。
