### ISSUE TITLE
map question

### ISSUE THREAD

**Issue by sc199505** [sfzhang15/RefineDet#187]
Hello, when I trained a 5 class detector with my own data, I found that the map value is not as high as the SSD during the training, but the AP value of each category is evener than the SSD. Is it the number of times I have iterated? Not enough? Thank you for your convenience.

**Comment by sfzhang15** [comment]
@sc199505 
I do not understand your question. Please describe it more clearly.

**Comment by sc199505** [comment]
Thank you for your answer. I've found the reason for the question. It's the threshold question.
