### ISSUE TITLE
very very very very good job!!!

### ISSUE THREAD

**Issue by CrazySssst** [sfzhang15/RefineDet#19]
thanks for your great job !  i think it is a significant advance for one-stage method. 
my question is that why only use three anchors [1,1\2,2] 
 Do you try more anchors?

**Comment by sfzhang15** [comment]
@CrazySssst Hi, thank you !
Due to time and computational resources limitations, we have not tried more anchors. According to the previous works, we think that properly increasing the number of anchors can get better results, but the speed will also be slightly slower.
