### ISSUE TITLE
batch inference issue

### ISSUE THREAD

**Issue by stigma0617** [sfzhang15/RefineDet#191]
Hi,

I tried to infernce batch images using [these lines in refinedet_demo.py](https://github.com/sfzhang15/RefineDet/blob/master/test/refinedet_demo.py#L102-L120)

```
for idx, img in enumerate(im_names):
    ...
    net.blobs['data'].data[idx, :, :,:] = transformed_image

detections = net.forward()['detection_out']

for idx in range(len(im_names)):
    det_label = detection[idx, 0, :, 1] # error occurs!!
```

This code results in errors because the detection dimension is [1,1,#outputs, 7]

I expected the first dimension is the number of batch and tried to split each detection result per image.

What should I do to inferecne batch images?

**Comment by sfzhang15** [comment]
@stigma0617 
The number of batch is not the first dimension. It is the first index of the final dimension as [this](https://github.com/sfzhang15/RefineDet/blob/master/src/caffe/layers/detection_output_layer.cpp#L174-L175).

**Comment by stigma0617** [comment]
@sfzhang15 thanks for your help!
