### ISSUE TITLE
About Tranfer Connection Block

### ISSUE THREAD

**Issue by ZhiweiYan-96** [sfzhang15/RefineDet#193]
Hi Dr Zhang !
Thanks for your great work! 
Recently I am trying to modify RefineDet. I found that TCB is quite important for cascade regression. Do you have any special consideration for top-down like TCB module design (e.g. getting global information)? 
As for my experiments, i found that if i only use features at same level(like add an extra conv on origin prediction layer), the detection performance would become worse. So i think TCB is quite an important block.  If you design for ths bolck for some speicific purpose, could you give me some instruction?

**Comment by sfzhang15** [comment]
@14zwyan 
The TCB is similar as FPN. We want to use better features to perform the second detection stage that is more difficult.

**Comment by sfzhang15** [comment]
I close this issue because there was no response for a long time, please reopen it if there are still problems.

**Comment by ZhiweiYan-96** [comment]
Thank you for your kind reply!
