### ISSUE TITLE
More bounding boxes in images with people

### ISSUE THREAD

**Issue by mdrpanwar** [sfzhang15/RefineDet#194]
Hi Shifeng!
Thanks a lot for this great work. I have encountered an issue with images having persons. When the images contain a lot of people (or people present close together), the model outputs more bounding boxes than the number of persons present in the image. Have you observed this? Any suggestions on how can I go about rectifying/improving it?
Thanks.

**Comment by sfzhang15** [comment]
@mdrpanwar 
It is about the dense object detection, you can refer to [some pedestrian/person methods](https://bitbucket.org/shanshanzhang/citypersons/src/default/) to improve the performance.

**Comment by sfzhang15** [comment]
I close this issue because there was no response for a long time, please reopen it if there are still problems.
