### ISSUE TITLE
Simple C++ implementation of any object classification 

### ISSUE THREAD

**Issue by shalinsirwani** [sfzhang15/RefineDet#195]
Please provide implementation in c++ for any object classification ...

**Comment by sfzhang15** [comment]
@shalinsirwani 
You can refer to [this](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_detect.cpp).

**Comment by sfzhang15** [comment]
I close this issue because there was no response for a long time, please reopen it if there are still problems.
