### ISSUE TITLE
how to create single_test_deploy.prototxt

### ISSUE THREAD

**Issue by shixinlishixinli** [sfzhang15/RefineDet#196]
hi 

i want to use the refinedet_test.py to test the mAP of the model , and i copy the single_test_deploy.prototxt from deploy.prototxt. the error is TypeError: 'float' object has no attribute '__getitem__' . the mAP is {120000: 0.0}. is the single_test_deploy.prototxtn right? how to solve this issue?

best
lisa shi

**Comment by sfzhang15** [comment]
@shixinlishixinli 
Please follow the evaluation steps in README to test our provided models.

**Comment by shixinlishixinli** [comment]
hi 
thank you for your reply . and i follow the readme to test models . i can test voc successfully . but i also can not test coco successfully . the error is " TypeError: 'float' object has no attribute 'getitem' "
best
lisa shi

**Comment by sfzhang15** [comment]
@shixinlishixinli 
Sorry about the late reply. Has the problem been solved?
