### ISSUE TITLE
Does it require Nvidia GPU to run?

### ISSUE THREAD

**Issue by kaishijeng** [sfzhang15/RefineDet#2]
It seems your code requires Nvidia GPU to run Is there a way to run it without GPU?

Thanks,

**Comment by sfzhang15** [comment]
@kaishijeng 
Our code is based on caffe and you can run it with CPU via 'caffe.set_mode_cpu()'. Meanwhile you can build the code only with CPU support. But using CPU is slow, because both VGG-16 and ResNet-101 is time-consuming on CPU devices. We suggest that you use the GPU to run the code.

**Comment by sfzhang15** [comment]
Sorry, we have not yet planned to use MobileNet as the base network. You can use our code to train it. If you have questions, please feel free to contact.
