### ISSUE TITLE
NameError: global name 'DeconvBNLayer' is not defined

### ISSUE THREAD

**Issue by foralliance** [sfzhang15/RefineDet#20]
编译/数据集/预训练模型都已准备完，执行python examples/refinedet/VGG16_VOC2007_320.py
时，提示：
Traceback (most recent call last):
  File "examples/refinedet/VGG16_VOC2007_320.py", line 430, in <module>
    AddExtraLayers(net, use_batchnorm, arm_source_layers, normalizations, lr_mult=lr_mult)
  File "examples/refinedet/VGG16_VOC2007_320.py", line 61, in AddExtraLayers
    DeconvBNLayer(net, from_layer, out_layer, use_batchnorm, False, 256, 2, 0, 2, lr_mult=lr_mult)
NameError: global name 'DeconvBNLayer' is not defined

**Comment by sfzhang15** [comment]
@foralliance Hi
The DeconvBNLayer function is defined at ./python/caffe/model_libs.py, you can check whether the path of this file is correct.

**Comment by foralliance** [comment]
@sfzhang15  Hi
I tried a lot of methods．
I found under my configuration, "DeconvBNLayer"，"EltwiseLayer"，"CreateRefineDetHead" .these three functions can't import

**Comment by sfzhang15** [comment]
@foralliance Hi
Maybe you have fixed your own PYTHONPATH. You can try to modify the 'sys.path.append("./python")' to 'sys.path.insert(0,"./python")' at the 'examples/refinedet/VGG16_VOC2007_320.py'.

**Comment by foralliance** [comment]
@sfzhang15  Hi
The problem solved!!
Thank you for your patience!!!

**Comment by sfzhang15** [comment]
@foralliance 
We have encountered this problem before. Happy to help you solve the problem.
