### ISSUE TITLE
What‘s the difference between ARM and RPN

### ISSUE THREAD

**Issue by zl1994** [sfzhang15/RefineDet#21]
Hi, 
   Can you tell me the difference between ARM and RPN?

**Comment by sfzhang15** [comment]
@zl1994 Hi
ARM is designed to (1) identify and remove negative anchors to reduce search space for the classifier, and (2) coarsely adjust the locations and sizes of anchors to provide better initialization for the subsequent regressor. ODM takes the refined anchors as the input from the former to further improve the regression and predict multi-class labels. The difference between ARM and RPN are follows:
1. **Two-stage classification**: ARM focuses on the binary classification (being an object or not), while ODM are trained for the multi-class classification (background or object classes).
2. **Two-stage regression**: ARM regresses from anchor to GT, while ODM regresses from the regression results of ARM to GT to get better localization.
3. **Two-stage feature**: Comparing with AEM, the feature in ODM is richer and better for the more challenging tasks.

**Comment by ashkanaev** [comment]
@sfzhang15, Hello
Thank you for such interesting and valuable work.
Have you tried use focal loss loss function for classification? It's help's to keep balance between negative and target too.

**Comment by sfzhang15** [comment]
@ashkanaev ,Hi
Thanks.
Until now, we do not try to use the focal loss function. As we said in our paper, we think that the focal loss is complementary to our method. We believe that replacing OHEM with the focal loss can further improve the performance.
