### ISSUE TITLE
multi-scale training/testing

### ISSUE THREAD

**Issue by foralliance** [sfzhang15/RefineDet#22]
How to understand this sentence: The multi-scale testing is used to reduce the impact of input size for a fair comparison
why "multi-scale testing" can reduce the impact of input size?

another question is: how is multi-scale testing/training implemented?
1. train all the scales, so u had to train/test many times
2. randomly select a scale from multiple scales, so u only need to train/test once

**Comment by sfzhang15** [comment]
@foralliance , Hi
1. The input size significantly influences detection accuracy, since high resolution inputs make the detectors “seeing” small objects clearly to increase successful detections. The multi-scale testing can make the detector trained with limited input size (e.g., 320x320) to 'see' those small objects that only can be 'see' by the large input size (e.g., 1000x600). 
2. The multi scale training of RefineDet is the same as SSD, i.e., using the crop and expand operation. The multi scale testing code has already been provided at [test/refinedet_test.py](https://github.com/sfzhang15/RefineDet/blob/master/data/coco/README.md), you can refer to it for details.

**Comment by foralliance** [comment]
@sfzhang15 , Hi
from the code refinedet_test.py, i found, for voc dataset, in the single scale testing. No NMS related technologies is used. is right??

for bbox_vote or soft_bbox_vote, this should be an enhanced version of the NMS. In addition to using the NMS to exclude some boxes, the last remaining box coordinates are refined too. is right?

**Comment by sfzhang15** [comment]
@foralliance , Hi
1. The deploy.prototxt contains the detection_output_layer, which has the NMS operation.
2. Yes, It is. The last remaining box is resulted from the weighted average of all those boxes.

**Comment by foralliance** [comment]
@sfzhang15 ,Hi
For "soft_bbox_vote", it's a little hard to understand. Any relevant theoretical knowledge or paper??

**Comment by sfzhang15** [comment]
@foralliance , Hi
Supposed that you have understood the 'bbox_vote'. And the 'soft_bbob_vote' just combines the 'bbox_vote' with the idea of [soft-nms](https://arxiv.org/abs/1704.04503) that we do not directly delete those bbox but lower their score via the corresponding IoU.

**Comment by foralliance** [comment]
@sfzhang15 , Hi
many many thsnks

**Comment by xychen9459** [comment]
@sfzhang15, Hi

I have read your multiscale testing code and have a question about parameter setting. 

In function `multi_scale_test_net_320()`, 6 different input scales (0.6x, 1.2x, 1.4x, 1.6x, 1.8x, 2.2x) are used for testing. After detection, the following codes are used for refining outputs:
```
...
# for 0.6x input size
index = np.where(np.maximum(det1[:, 2] - det1[:, 0] + 1, det1[:, 3] - det1[:, 1] + 1) > 32)[0]
...
# for 1.2x input size
index = np.where(np.minimum(det2[:, 2] - det2[:, 0] + 1, det2[:, 3] - det2[:, 1] + 1) < 160)[0]
...
# for 1.4x input size
index = np.where(np.minimum(det3[:, 2] - det3[:, 0] + 1, det3[:, 3] - det3[:, 1] + 1) < 128)[0]
...
# for 1.6x input size
index = np.where(np.minimum(det4[:, 2] - det4[:, 0] + 1, det4[:, 3] - det4[:, 1] + 1) < 96)[0]
...
# for 1.8x input size
index = np.where(np.minimum(det5[:, 2] - det5[:, 0] + 1, det5[:, 3] - det5[:, 1] + 1) < 64)[0]
...
# for 2.2x input size
index = np.where(np.minimum(det7[:, 2] - det7[:, 0] + 1, det7[:, 3] - det7[:, 1] + 1) < 32)[0]
...
```
In addition, some detection outputs are not suppressed as above codes in function `multi_scale_test_net_512()`. 

I wonder how these bbox size thresholds and refine strategies are chosen. Thanks.

**Comment by larsoncs** [comment]
@sfzhang15  the multi scale train code  was not been provided，can you release the code，thank you!

**Comment by sfzhang15** [comment]
@foralliance 
The multi scale testing code is provided and you can find it at [here](https://github.com/sfzhang15/RefineDet/blob/master/test/refinedet_test.py).

**Comment by larsoncs** [comment]
@sfzhang15 ，I  mean that the multi-scale train code is not released, not yet test code, thx.

**Comment by sfzhang15** [comment]
@foralliance 
We use the data augmentation from SSD to train our model, including distortion, croppin, expanding and flipping. The cropping and expanding correspond to multi-scale training. You can refer to [here](https://github.com/sfzhang15/RefineDet/blob/master/src/caffe/layers/annotated_data_layer.cpp#L155-L186).

**Comment by Karthik-Suresh93** [comment]
Hi @sfzhang15 ,

Can you please clarify why you use nms/soft_nms for single scale testing and bbox_vote/soft_bbox_vote for multi-scale testing as shown here:
https://github.com/sfzhang15/RefineDet/blob/fa155e265cba7f51e25a4006ee2f32e9097e1eb7/test/lib/fast_rcnn/test.py#L324

I am trying to implement multi-scale testing in my own project following the approach:

- Stack detections from all scales

- Run NMS on the stacked detections

Unfortunately this is not working even though it is fine on a single scale. Please clarify this issue. Any advice will be greatly appreciated

**Comment by keyang1** [comment]
hello， @sfzhang15 I use the refinedet_test.py to do multi-scale testing ,but there  has a wrong:
Check failed: bottom[i]->shape() == bottom[0]->shape() ,but when I use the single-scale testing,there will don't have the problem,can you help me?

**Comment by sfzhang15** [comment]
@keyang1 
What modifications have you made? Codes? Data? Model?

**Comment by keyang1** [comment]
> @keyang1
> What modifications have you made? Codes? Data? Model?
thank you for your help ,I change the model ,so the scale of the feature map  is not matched,so I think I should change the code .

**Comment by keyang1** [comment]
@sfzhang15 
Thank you for your help ,I change the model ,so the scale of the feature map is not matched,so I think I should change the code .
