### ISSUE TITLE
normalize_layer

### ISSUE THREAD

**Issue by auroua** [sfzhang15/RefineDet#23]
In the `normalize_layer.cpp`,  https://github.com/sfzhang15/RefineDet/blob/592bbc1f95fe095953ac4b35ad93d42460272d79/src/caffe/layers/normalize_layer.cpp#L109-L115
The code is not a standard L2-norm. You only added the different channel and then sqrt the data. Why not using standard L2-norm?

**Comment by sfzhang15** [comment]
@auroua , Hi
The normalize_layer.cpp is introduced by [this paper](https://arxiv.org/abs/1506.04579). You can refer to it for details.

**Comment by auroua** [comment]
I have read this paper, the paper use standard L2-norm.
![tim 20171229080931](https://user-images.githubusercontent.com/2869412/34432501-c3ad6280-ecb2-11e7-985a-8338080deded.png)
The code in `normalize_layer.cpp` is different from the paper.

**Comment by sfzhang15** [comment]
@auroua 
The normalize_layer.cpp is the standard L2-norm, but it does L2-norm per each pixel in a feature map instead of the whole. Just as the paper says:
![image](https://user-images.githubusercontent.com/31090111/34456914-77b14a3c-eddd-11e7-9086-d19d8269f6c9.png)

**Comment by auroua** [comment]
If the feature map is `[batch_size, 5, 5, 3]`, and the three channels is `[x, y, z]`.
In position `[0, 0]` , the normalize should be  
`[x[0, 0], y[0, 0], z[0, 0]]/math.sqrt(x[0, 0]^2 + y[0, 0]^2 + z[0, 0]^2)`.
but the code is 
`[x[0, 0], y[0, 0], z[0, 0]]/math.sqrt(x[0, 0] + y[0, 0] + z[0, 0])`.
I don't know why the code in `normalize_layer.cpp` is this form.

**Comment by sfzhang15** [comment]
@auroua 
The line 101 'caffe_sqr<Dtype>(dim, bottom_data, buffer_data)' is for x[0, 0]^2, y[0, 0]^2, z[0, 0]^2.

**Comment by auroua** [comment]
@sfzhang15 
😰 😰 
Thanks
