### ISSUE TITLE
detection_output_layer is only supported on cpu

### ISSUE THREAD

**Issue by jinxuan777** [sfzhang15/RefineDet#24]
hi @sfzhang15 ,I found DetectionOutput only supported on cpu without detection_output_layer.cu . In resize 512*512, the FPS of refineDet is higher than SSD(24 vs 19 ).Maybe Faster move to gpu?

**Comment by sfzhang15** [comment]
@jinxuan777 
Thanks! We will release the 'detection_output_layer.cu' later.

**Comment by sfzhang15** [comment]
@jinxuan777 , Hi
We have modified and added some codes to make DetectionOutput supported on GPU. Thanks.
