### ISSUE TITLE
Layer weight copy mismatch

### ISSUE THREAD

**Issue by yuanyc06** [sfzhang15/RefineDet#25]
Hi @sfzhang15 , I tried to finetune my own model with the scripts generated by examples/refinedet/finetune_VGG16_VOC2012_320.py and models/VGGNet/VOC0712/refinedet_vgg16_320x320_coco/coco_refinedet_vgg16_320x320.caffemodel. But when I run the training with train.prototxt, it said:

Cannot copy param 0 weights from layer 'P3_mbox_conf'; shape mismatch.  Source param shape is 63 256 3 3 (145152); target param shape is 6 256 3 3 (13824). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.

Do you know what's wrong? Thank you!

**Comment by sfzhang15** [comment]
@yuanyc06 , Hi
We download the codes and the models, then run the scripts. It is run correctly as follow：
![Uploading image.png…]()
So the provided codes and models maybe should be right. Have you modified somethings? The source and target param shape of  'P3_mbox_conf' should all be  63 256 3 3 (145152).

**Comment by yuanyc06** [comment]
@sfzhang15 Thank you for your reply! Now I've found the problem: I was doing a 2-class model instead of 21, which caused the dimension mismatch. I've modified the code and now it run's well.
