### ISSUE TITLE
FPS of RefineDet

### ISSUE THREAD

**Issue by jinxuan777** [sfzhang15/RefineDet#28]
nice jobs！Have you test the FPS and Boxes of RefineDet512（resnet-101） @sfzhang15 ？

**Comment by sfzhang15** [comment]
@jinxuan777 Hi, just now, we test the FPS of RefineDet512 (res-101) on TITAN X（maxwell）with CUDA 8.0 and CUDNN 6.0. Its FPS is about 8.
