### ISSUE TITLE
Merge to my own caffe

### ISSUE THREAD

**Issue by yuanyc06** [sfzhang15/RefineDet#29]
Hi @sfzhang15 , I've trained your method on my own dataset and it works pretty well. Now that I'd like to merge the related code to my own Caffe, do you know what layers/files I need to copy/modify? As far as I can tell, there is no new layer used during training/testing, and a new "objectness_score" parameter is added in src/caffe/proto/caffe.proto (line 1038 and 1319)

**Comment by sfzhang15** [comment]
@yuanyc06 Hi,
The version of the route is "Official caffe -> SSD's caffe -> RefineDet's caffe". There is lots of modifications between official caffe and SSD's caffe , we suppose your own caffe is the same as SSD's caffe. As for the difference between SSD's caffe and RefineDet's caffe, you can use the comparison software (e.g., meld) to find them. We do not add new layers but modify some existing layer.

**Comment by yuanyc06** [comment]
Thanks, my caffe is based on the SSD version. Do the modifications of RefineDet incrememental to the original SSD? i.e. has no influence to the usage of SSD or other standard networks?

**Comment by sfzhang15** [comment]
@yuanyc06 
Yes, the modifications of RefineDet is compatible with the original SSD.

**Comment by yxchng** [comment]
@sfzhang15 Is the changes in SSD caffe non compatible with the original caffe such that it will not be possible to merge them?

**Comment by sfzhang15** [comment]
@yxchng 
The RefineDet is compatible with the original SSD. You can run SSD successfully with the RefineDet code.

**Comment by yxchng** [comment]
I know that it is compatible with SSD but my current program is using the official caffe and I am wondering if your Caffe is compatible with the official one.

**Comment by sfzhang15** [comment]
@yxchng 
Our caffe is based on the caffe from SSD. The SSD implents some new layers and functions, so maybe it is not compatible with the official one.

**Comment by yxchng** [comment]
Ok thanks.
