### ISSUE TITLE
Can not download the model in China

### ISSUE THREAD

**Issue by hezhenjun123** [sfzhang15/RefineDet#3]
国内貌似下载不了那几个模型文件，可以提供个不被墙的下载链接么？ 谢谢

**Comment by sfzhang15** [comment]
@hezhenjun123 
OK, we are uploading the model files to BaiduNetdisk. Later we will provide the link.

**Comment by sfzhang15** [comment]
@hezhenjun123 
The download link of BaiduYun is provided at the end of README.

**Comment by hezhenjun123** [comment]
@sfzhang15 谢谢，看了几篇你最近发的3篇论文（faceboxes，SFD，RefineDet），都非常有价值，辛苦了

**Comment by sfzhang15** [comment]
Thanks.
