### ISSUE TITLE
Is the training process as the same with faster rcnn?

### ISSUE THREAD

**Issue by junjieAI** [sfzhang15/RefineDet#32]
And the follow step is necessary?Thanks
 3Create the LMDB file.

# You can modify the parameters in create_data.sh if needed.
# It will create lmdb files for trainval and test with encoded original image:
#   - $HOME/data/VOCdevkit/VOC0712/lmdb/VOC0712_trainval_lmdb
#   - $HOME/data/VOCdevkit/VOC0712/lmdb/VOC0712_test_lmdb
# and make soft links at examples/VOC0712/
cd $RefineDet_ROOT
./data/VOC0712/create_data.sh

**Comment by sfzhang15** [comment]
@junjieAI Hi,
The faster rcnn input directly reads the image, while the SSD input is from lmdb, so you need to create the lmdb firstly following the instruction.

**Comment by junjieAI** [comment]
@sfzhang15 
Thanks , I've done this
