### ISSUE TITLE
when use finetune_VGG16_VOC2012_320.py train model this kind of error happens

### ISSUE THREAD

**Issue by junjieAI** [sfzhang15/RefineDet#34]
@sfzhang15 
Hi, my friend also have tried, and he use 320*320 following the step I used to train 512*512, but he got a problem as follow, it is appreciated that if you can give some helps.

I0128 22:00:27.281307  5775 layer_factory.hpp:77] Creating layer arm_conf_flatten
I0128 22:00:27.281316  5775 net.cpp:100] Creating Layer arm_conf_flatten
I0128 22:00:27.281322  5775 net.cpp:434] arm_conf_flatten <- arm_conf_softmax
I0128 22:00:27.281328  5775 net.cpp:408] arm_conf_flatten -> arm_conf_flatten
I0128 22:00:27.281378  5775 net.cpp:150] Setting up arm_conf_flatten
I0128 22:00:27.281399  5775 net.cpp:157] Top shape: 8 12750 (102000)
I0128 22:00:27.281401  5775 net.cpp:165] Memory required for data: 2383611300
I0128 22:00:27.281406  5775 layer_factory.hpp:77] Creating layer odm_loss
I0128 22:00:27.281430  5775 net.cpp:100] Creating Layer odm_loss
I0128 22:00:27.281433  5775 net.cpp:434] odm_loss <- odm_loc
I0128 22:00:27.281440  5775 net.cpp:434] odm_loss <- odm_conf
I0128 22:00:27.281443  5775 net.cpp:434] odm_loss <- arm_priorbox_arm_priorbox_0_split_1
I0128 22:00:27.281447  5775 net.cpp:434] odm_loss <- label_data_1_split_1
I0128 22:00:27.281450  5775 net.cpp:434] odm_loss <- arm_conf_flatten
I0128 22:00:27.281453  5775 net.cpp:434] odm_loss <- arm_loc_arm_loc_0_split_1
I0128 22:00:27.281460  5775 net.cpp:408] odm_loss -> odm_loss
I0128 22:00:27.281520  5775 layer_factory.hpp:77] Creating layer odm_loss_smooth_L1_loc
I0128 22:00:27.281627  5775 layer_factory.hpp:77] Creating layer odm_loss_softmax_conf
I0128 22:00:27.281647  5775 layer_factory.hpp:77] Creating layer odm_loss_softmax_conf
F0128 22:00:27.281867  5775 multibox_loss_layer.cpp:141] Check failed: num_priors_ * num_classes_ == bottom[1]->channels() (133875 vs. 12750) Number of priors must match number of confidence predictions.
*** Check failure stack trace: ***

**Comment by sfzhang15** [comment]
@junjieAI Hi, we have successfully run the finetune_VGG16_VOC2012_320.py just now. The bottom[1] of odm_loss is odm_conf, its channels() should be 6375 * 21, but yours is 6375 * 2. We think you mistake the conf output of P3, P4, P5, P6. Please check it.

**Comment by junjieAI** [comment]
@sfzhang15 
But his num_classes are 2, so shouldn't we change the num_classes from 21 to 2?

**Comment by sfzhang15** [comment]
@junjieAI 
If you train the model on the other dataset, some parameters should be changed correspondingly.

**Comment by junjieAI** [comment]
@sfzhang15 
hi, so what else parameters should be changed if we use other dataset and with different number of class? thanks for your help!

**Comment by sfzhang15** [comment]
@junjieAI 
Except num_class, the ratio aspect and scale of anchors maybe need to change according to your dataset to get better performance.

**Comment by junjieAI** [comment]
@sfzhang15 
    Hello, I'm terribly sorry to disturb you again. Back to the above problem that my friend met, I tried finetune_VGG16_VOC2012_320.py too just now, but also failed, the difference between us only the num_classes(my classes are 12, and his classes are 2), both of us are only changed "num_classes==21 to ours(me:12 and he:2)" in finetune_VGG16_VOC2012_320.py file.
     And we met the same problem: "Check failed: num_priors_ * num_classes_ == bottom[1]->channels() (133875 vs. 76500) Number of priors must match number of confidence predictions." as you said mine is  6375 * 12 , and my friend is 6375 * 2, and here the 12 ,2 shouldn't be the actual number of our own classes? must be 21?
    While in the finetune_VGG16_VOC2012_512.py, we also did the same(just changed the num_classes), but both of us run successfully

**Comment by sfzhang15** [comment]
@junjieAI 
We change the num_class from 21 to 12, it also run successfully without error messages. According to your error message, the shape of your odm_conf is correct (i.e., 76500), but the num_priors_*num_classes_=6375*21=133875 is wrong, it should be 6375*12= 76500. So the ‘num_classes_’ is wrong, it is 21, but should be 12. You should check out why the 'num_classes_' is changed correspondingly.

**Comment by junjieAI** [comment]
@sfzhang15 
hi, thanks for your patient instruction, the problem has gone, by the way, you just change the num_class from 21 to 12 in finetune_VGG16_VOC2012_320.py？
But another error occurs, I don't know what to say！!! ：
I0129 21:00:17.936637 17171 net.cpp:228] data does not need backward computation.
I0129 21:00:17.936640 17171 net.cpp:270] This network produces output arm_loss
I0129 21:00:17.936642 17171 net.cpp:270] This network produces output odm_loss
I0129 21:00:17.936758 17171 net.cpp:283] Network initialization done.
I0129 21:00:17.937156 17171 solver.cpp:75] Solver scaffolding done.
I0129 21:00:17.943174 17171 caffe.cpp:155] Finetuning from models/VGGNet/VOC0712/refinedet_vgg16_320x320/VOC0712_refinedet_vgg16_320x320_final.caffemodel
F0129 21:00:18.027642 17171 net.cpp:767] Check failed: target_blobs.size() == source_layer.blobs_size() (1 vs. 2) Incompatible number of blobs for layer conv6_1

**Comment by sfzhang15** [comment]
@junjieAI 
If you change the num_class from 21 to 12 in finetune_VGG16_VOC2012_320.py, you can not directly fine-tune from 'VOC0712_refinedet_vgg16_320x320_final.caffemodel' or other provided models, since the output channel number of conf layers will be not matched. You should change the name of the conf layers.
By the way, according to the error message, the number blobs of conv6_1 is wrong ,we do not know the cause of this problem.

**Comment by sfzhang15** [comment]
@junjieAI 
If your 12 classes is the subset of voc 21 classes, you can convert the model, just like converting from coco to voc.
