### ISSUE TITLE
failed to upload the results on test-dev2017

### ISSUE THREAD

**Issue by youngwanLEE** [sfzhang15/RefineDet#36]
Hi, Did you try to upload the results on coco evaluation server recently ?

I have tried to upload the results on test-dev2017(same as test-dev2015).

By using your refinedet_test.py, I got the result json file(1.33GB). 

However, I could't upload the result file(.zip) on that server. Perhaps, the file size is so big.

Could you advice for me to downsize the json file ?

**Comment by sfzhang15** [comment]
@youngwanLEE Hi, the coco server has size limitation of submission. You can downsize the json file by  increasing confidence_threshold.

**Comment by youngwanLEE** [comment]
Could you suggest the reasonable confidence_threshold?

**Comment by sfzhang15** [comment]
@youngwanLEE 
According to our experience, every model has different optimal confidence_threshold. For every model, we test it with some confidence_threshold to submit and choose the best one as the final confidence_threshold.

**Comment by youngwanLEE** [comment]
@sfzhang15 Thanks for your constructive answers.
