### ISSUE TITLE
How to evaluate VOC2012 test?

### ISSUE THREAD

**Issue by youngwanLEE** [sfzhang15/RefineDet#37]
Hi, 

Recently, I have researched my backbone networks and replaced my networks with Res101 in your RefineDet.

I tried to upload VOC2012 test results. So by using the refinedet_test.py, I got the detections.pkl file.

Then, I don't know how to deal with that results.pkl file. 

Could you let me know how to upload VOC2012 test results?

Thanks in advance.

**Comment by sfzhang15** [comment]
@youngwanLEE 
After using the refinedet_test.py, the detection results is saved at your VOCdevkit folder, i.e., ****/results, you should zip this folder and submit to the voc 2012 server for evaluation.

**Comment by youngwanLEE** [comment]
Thanks for your reply :)
