### ISSUE TITLE
how do i define arm/odm_source_layers for other networks

### ISSUE THREAD

**Issue by navneet1083** [sfzhang15/RefineDet#38]
Hi, how do i choose *_source_layers for other networks (like deepnet; inception; etc).

**Comment by sfzhang15** [comment]
@navneet1083 Hi,
Every source layers of ARM and ODM should have the same height, width, channel.  For other base networks, you should use deconv to get some layers whose sizes are the same as base network, and then choose arm_source_layers from base network and odm_source_layers from those deconv layers, just like VGG16.
