### ISSUE TITLE
Number of Boxes about yolo v2

### ISSUE THREAD

**Issue by ujsyehao** [sfzhang15/RefineDet#40]
Hi, In yolo v2:
416x416 input: boxes = (416/32)*(416/32)*5=13*13*5=845
544x544 inut: boxes = (544/32)*(544/32)*5=17*17*5=1445
So in Readme.md, yolo v2 544x544 number o Boxes should be 1445

**Comment by sfzhang15** [comment]
@ujsyehao Thanks！
