### ISSUE TITLE
F0325 db_lmdb.hpp:15] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory 

### ISSUE THREAD

**Issue by datamonday** [sfzhang15/RefineDet#41]
when i run ssd_pascal.py to train VOC, I got this error:
I0325 22:45:37.875373 3664 layer_factory.hpp:77] Creating layer data
I0325 22:45:37.882928 3664 net.cpp:100] Creating Layer data
I0325 22:45:37.883014 3664 net.cpp:408] data -> data
I0325 22:45:37.883144 3664 net.cpp:408] data -> label
F0325 22:45:37.885095 3685 db_lmdb.hpp:15] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
@ 0x7f022621c5cd google::LogMessage::Fail()
@ 0x7f022621e433 google::LogMessage::SendToLog()
@ 0x7f022621c15b google::LogMessage::Flush()
@ 0x7f022621ee1e google::LogMessageFatal::~LogMessageFatal()
@ 0x7f0226ab42f0 caffe::db::LMDB::Open()
@ 0x7f0226b216d6 caffe::DataReader<>::Body::InternalThreadEntry()
@ 0x7f02268ed725 caffe::InternalThread::entry()
@ 0x7f021a5c15d5 (unknown)
@ 0x7f0214c006ba start_thread
@ 0x7f022527341d clone
@ (nil) (unknown)
Aborted (core dumped)
and when i try to open VOC0712_test_lmdb, it tells me this:

The link "VOC0712_test_lmdb" is broken,Move it to Trash?
This link cannot be used because its target “/home/chopin/data/VOCdevkit/VOC0712/lmdb/VOC0712_test_lmdb” doesn't exist.

I'm confused by this problem a few days , and i found many ask, such as edit path in prototxt files,but this problm still occured. I can run ssd in picture webcam video normally. thanks! Please help me,thanks!

**Comment by datamonday** [comment]
Checking a lot of them is a path problem, but I found that the path looks like no problem, and no changes have been made after the compilation.But I try to open examples/VOC0712_test_lmdb，I got this tip: "The link “VOC0712_test_lmdb” is broken. Move it to Trash? This link cannot be used because its target “/home/chopin/data/VOCdevkit/VOC0712/lmdb/VOC0712_test_lmdb” doesn't exist. "

I run ./data/VOC0712/create_data.sh got this feedback but its normal and creat lmdb correctly?

/home/chopin/caffe/build/tools/convert_annoset --anno_type=detection --label_type=xml --label_map_file=/home/chopin/caffe/data/VOC0712/../../data/VOC0712/labelmap_voc.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/chopin/data/VOCdevkit/ /home/chopin/caffe/data/VOC0712/../../data/VOC0712/test.txt /home/chopin/data/VOCdevkit/VOC0712/lmdb/VOC0712_test_lmdb
/home/chopin/caffe/build/tools/convert_annoset --anno_type=detection --label_type=xml --label_map_file=/home/chopin/caffe/data/VOC0712/../../data/VOC0712/labelmap_voc.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/chopin/data/VOCdevkit/ /home/chopin/caffe/data/VOC0712/../../data/VOC0712/trainval.txt /home/chopin/data/VOCdevkit/VOC0712/lmdb/VOC0712_trainval_lmdb

If the path wrong to result in this error, what path and profile I should to edit? I will be very grateful if you are willing to help me.Thanks again!

**Comment by datamonday** [comment]
I check the /home/chopin/data/VOCdevkit/VOC0712/lmdb  but it has nothing! what's wrong and what should i  do?

**Comment by sfzhang15** [comment]
@datamonday 
You do not creat the lmdb successfully. Please follow the steps in SSD to creat the lmdb.
