### ISSUE TITLE
Just Train Network for Person Detection

### ISSUE THREAD

**Issue by ahkarami** [sfzhang15/RefineDet#42]
Dear @sfzhang15,
Thank you for your work. I have a general question. In the **VOC** and **COCO** datasets there are some classes (_e.g.,_ 20 or 80 classes (person, car, horse, etc.) for object detection). If one train the network **just** for one class (_e.g.,_ just the person class) will the accuracy (mAP) of person detection increase?

**Comment by sfzhang15** [comment]
@ahkarami Hi,
We are not sure whether it will increase the accuracy. But if you want to train the method for person detection, you should use the specific datasets, i.e., CityPersons, Catech and so on. Besides, you should adjust some parameters correspondingly, i.e., anchor scales, anchor ratios, learning rate, etc. We have the plan to train our RefineDet for pedestrian detection.

**Comment by ahkarami** [comment]
@sfzhang15,
Thank you for your reply. I hope your trained model for person detection with its interesting results prepare soon. 
As you have excellent knowledge and experience in object detection, I want to know that, generally if we reduce the number of classes in a data set, will this increase the accuracy of detection? (for example instead of train the model on all 20 classes in VOC data set, just train it on 1 class). However, I think, as your previous answer, you are not sure about the answer of this question.
Excuse me for my inconvenience, I have two more questions. 
1- Regarding your above answer, you mean that the VOC & COCO data sets are not appropriate data sets for person detection (and for example CityPersons and so on, are proper)? 
2- What's your opinion about [_Open Images_](https://github.com/openimages/dataset) data set? [its quality for person detection task]
Thank you

**Comment by sfzhang15** [comment]
@ahkarami 
Fisrtly, I want to emphasize the difference between pedestrian detection and person detection. Pedestrian detection only focuses on walking person, which are standing and has a roughly fixed aspect ratio, such as 0.41. While person detection aims at finding all kinds of person, i.e., pedestrain, riders, sitting person, unusual person and so on. If you only want to detect pedestrian, you should use those pedestrian detection datasets, such as citypersons and caltech. If you want to detect person, you can use those datasets which has the person class.
