### ISSUE TITLE
What batch size you use for using ResNet-101?

### ISSUE THREAD

**Issue by youngwanLEE** [sfzhang15/RefineDet#43]
Hi,

When I set the batch size 20 in [your code](https://github.com/sfzhang15/RefineDet/blob/master/examples/refinedet/ResNet101_COCO_512.py#L319), out of memory problem happened on TITAN X GPU(4GPU machine).

Perhaps, 5 per a GPU batch could be not fetched. 

How to set batch size in your case and training environment on 512? and Can I get the exact results(36.4%) on COCO512 following the your code setting such as multi_step_value:[400k: 480k: 540k] and batch size? or other training details? 

------------------------------------------------------------------------------------------------------------------
When I tried to train [your code](https://github.com/sfzhang15/RefineDet/blob/master/examples/refinedet/ResNet101_COCO_512.py) on P40 GPUs(24GB memory), this model occupied about 20-21GB memory on each GPU.

![image](https://user-images.githubusercontent.com/13238578/38542847-ecbab1b6-3cdd-11e8-80c8-6374e632d1ae.png)

**Comment by sfzhang15** [comment]
@youngwanLEE We train COCO_ResNet-101_512 with batch size=20 and  multi_step_value:[400k: 480k: 540k] on 4 24G/GPUs, i.e., each GPU has 5 images.

**Comment by youngwanLEE** [comment]
@sfzhang15 thanks for reply 👍
