### ISSUE TITLE
arm and odm  are all based on prior_bboxes in fucntion CasRegFindMatches ?

### ISSUE THREAD

**Issue by nopattern** [sfzhang15/RefineDet#46]
The odm location should be based on arm result in paper,but in CasRegFindMatches (),
`  if (!use_prior_for_matching) {
      for (int c = 0; c < loc_classes; ++c) {
        int label = share_location ? -1 : c;
        if (!share_location && label == background_label_id) {
          // Ignore background loc predictions.
          continue;
        }
        // Decode the prediction into bbox first.
        vector<NormalizedBBox> loc_bboxes;
        bool clip_bbox = false;
        DecodeBBoxes(prior_bboxes, prior_variances,
                     code_type, encode_variance_in_target
prior_bboxes, prior_variances,
                     code_type, encode_variance_in_target, clip_bbox,
                     all_loc_preds[i].find(label)->second, &loc_bboxes);
        MatchBBox(gt_bboxes, loc_bboxes, label, match_type,
                  overlap_threshold, ignore_cross_boundary_bbox,
                  &match_indices[label], &match_overlaps[label]);
      }`

The MultiBoxLoss laye of odm moudule  seems to be based on prior_bboxes instead of prior_bboxes + arm_loc because no arm parameters in DecodeBBoxes()?

**Comment by nopattern** [comment]
sorry find in CasRegDecodeBBoxesAll. close.

**Comment by sfzhang15** [comment]
@nopattern 
The 'use_prior_for_matching' is True, so the code will not run into this 'if' but the following 'else'. So we do not modify the code of this 'if' but the following 'else'.

**Comment by nopattern** [comment]
But the odm location should be based on arm_loc+prior_bboxes but instead of  based on original prior_bboxes as your paper suggested?
        I found odm location is based on arm module in function  CasRegDecodeBBoxesAll in test mode.So It is different in the train and test mode ?

**Comment by sfzhang15** [comment]
Both in the train and test mode, the odm location is based on arm_loc+prior_bboxes. In training, it is implented in [CasRegFindMatches](https://github.com/sfzhang15/RefineDet/blob/master/src/caffe/layers/multibox_loss_layer.cpp#L183). In testing, it is implented in [CasRegDecodeBBoxesAll](https://github.com/sfzhang15/RefineDet/blob/master/src/caffe/layers/detection_output_layer.cpp#L225) and [CasRegDecodeBBoxesGPU](https://github.com/sfzhang15/RefineDet/blob/master/src/caffe/layers/detection_output_layer.cu#L35).

**Comment by sfzhang15** [comment]
@nopattern 
All these function is located in the 'if and else', which means that if there is the input from arm, these above functions will be executed, versa vice.

**Comment by nopattern** [comment]
@sfzhang15  Thank you for your answer.
    The point is that I find CasRegFindMatches use only priorboxes but no arm_loc. Do I misread the code?But 2 calling of DecodeBBoxes in CasRegFindMatches are both based on priorboxes.

**Comment by sfzhang15** [comment]
@nopattern 
Yes, there are 2 calling of DecodeBBoxes based on priorboxes in CasRegFindMatches. The 2nd calling of DecodeBBoxes is used to get the arm_loc+prior_bboxes, then the following 'MatchBBox' will use the refined prior_bboxes to match. So the odm location is based on arm_loc+prior_bboxes for bbox matching.

**Comment by nopattern** [comment]
@sfzhang15 
 The 2nd calling of DecodeBBoxes is used to get the arm_loc+prior_bboxes, then the following 'MatchBBox' will use the refined prior_bboxes to match.
   But I think it should use refined prior_bboxes + odm_loc to match ?

**Comment by sfzhang15** [comment]
@nopattern 
the refined prior_bboxes + odm_loc is the final detection results.

**Comment by nopattern** [comment]
@sfzhang15 
    Got it .I misunderstand it before.Thank you very much.
