### ISSUE TITLE
Train in own dataset

### ISSUE THREAD

**Issue by HongyiDuanmu26** [sfzhang15/RefineDet#49]
Thank you for your great repo.
However, I want to know more instructions about how to train in my own dataset. What about the structure of the dataset file. I have images and annotations in .xml file. And it is just  a two class detection.

Thank you in advance.

**Comment by sfzhang15** [comment]
@HongyiDuanmu26 Hi
You should design the anchor (layers and scales) according to your datasets. Besides, the IoU threshold uesd to divide positive and negative samples can be adjusted properly.
