### ISSUE TITLE
source code comparing with original ssd

### ISSUE THREAD

**Issue by dremaker52** [sfzhang15/RefineDet#5]
Hi, I found no new layers compared with original ssd in prototxt so I wonder could I use the caffe built https://github.com/weiliu89/caffe/tree/ssd/examples/ssd here for experiments on this repo. Thanks.

**Comment by sfzhang15** [comment]
@dremaker52 
Hi, you can not use the caffe built from SSD, because we modify some layers and add some functions. You can use folder or file comparison tool to find these changes.

**Comment by dremaker52** [comment]
Thanks!
