### ISSUE TITLE
about odm

### ISSUE THREAD

**Issue by yuanCnD** [sfzhang15/RefineDet#53]
i just want to ask how many refined anchor boxes trans from arm to odm. for example, refinedet320, in arm stage, contains 6375 boxes. in this situation, how many refined anchors are left.

**Comment by sfzhang15** [comment]
@yuanCnD 
In our implementation, all the refined anchor boxes in the ARM will be sent to the ODM, then the ODM will filter out these easy negatives according to the scores from the ARM.

**Comment by yuanCnD** [comment]
thanks! it is helpful to do my research! As a reward, i should remind you that i think there is a small mistake in your v3 paper: in Figure 2, the kernal size of deconvlayer should be 2x2 , not 4x4.

**Comment by sfzhang15** [comment]
@yuanCnD 
According to [this issue](https://github.com/BVLC/caffe/pull/2213) and [FCN](https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/pascalcontext-fcn8s/train.prototxt), it may be 4x4.

**Comment by yuanCnD** [comment]
thanks a lot, that's my fault! in fcn, there is no padding param set. do you know why? is this means the default set is 1?

**Comment by sfzhang15** [comment]
@yuanCnD 
Maybe it has the [Crop operation](https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/pascalcontext-fcn8s/train.prototxt#L530).

**Comment by yuanCnD** [comment]
I really appreciate your guidance and help.
