### ISSUE TITLE
Training and testing on my own dataset

### ISSUE THREAD

**Issue by HongyiDuanmu26** [sfzhang15/RefineDet#56]
Hi, Thank you for your great work first!
I am running my own training on my own dataset and just a two classes detection. And now the problem is. I think I got trained prototext and cafffemodel successfully, but I don't know how to make detection on test set while I am not sure if you have saving json file or drawing bounding box part in text/refinedet_test.py. And refinedet_test.py are written just for VOC and COCO
So, could you provide advice about generating detection results based on trained caffemodel and dataset.

**Comment by whcjb** [comment]
Modified the model and src code according to the SFD method, using 6 layers' features.

**Comment by HongyiDuanmu26** [comment]
Yes, I trained successfully on my dataset and task. two class detection, final loss is about 1-2
Hopefully, I am not a  Liverpool fan. Otherwise I won't answer you. LOL.

**Comment by whcjb** [comment]
Thanks Duanmu. Look forward tonight. LOL^.^
