### ISSUE TITLE
Results of RefineDet-ResNet101

### ISSUE THREAD

**Issue by youngwanLEE** [sfzhang15/RefineDet#59]
Hi, I tried to train your RefineDet_ResNet101_VOC2007_320 referred to your code and got 79.77 mAP. 

How do you think this results? Could you compare with your own trained results?

**Comment by sfzhang15** [comment]
@youngwanLEE 
Hi, we think this result is reasonable, as shown in [DSSD](https://arxiv.org/abs/1701.06659) Table 3, the mAP of SSD_321_ResNet101 is slightly lower than SSD_300_VGG. Maybe the stride 2 in the first conv of ResNet is harmful, especially for the small input size.
