### ISSUE TITLE
‘AnnotatedDatum’ does not name a type

### ISSUE THREAD

**Issue by wait1988** [sfzhang15/RefineDet#60]
在编译项目的时候出现类似的一些错误，应该是当前项目里的caffe没有包含SSD里面的一些layer，大家下载下来的项目都可以正常编译么

**Comment by sfzhang15** [comment]
@wait1988 
你是不是装caffe2了？

**Comment by wait1988** [comment]
@sfzhang15 哈哈 对

**Comment by sdews** [comment]
重命名`/usr/local/include/caffe`，这样可以进行`make && make pycaffe`编译，但是`make test`会报错，因为编译器又首先在`/usr/local/include/`下找`gtest`， 因此还得重命名`/usr/local/include/gtest`. 更好的解决方法是修改Makefile的[一行](https://github.com/sfzhang15/RefineDet/blob/78c3701afc9d5b927b3c7b366ae33c5bbb8dbe2c/Makefile#L407):
即将
```
COMMON_FLAGS += $(foreach includedir,$(INCLUDE_DIRS),-isystem $(includedir))
```
修改为
```
COMMON_FLAGS += $(foreach includedir,$(INCLUDE_DIRS),-I $(includedir))
```
就是把参数`-isystem`改为`-I`. 又注意到，Makefile.config中[`INCLUDE_DIRS`](https://github.com/sfzhang15/RefineDet/blob/78c3701afc9d5b927b3c7b366ae33c5bbb8dbe2c/Makefile.config.example#L92)是系统目录，将参数`-isystem`改为`-I`后，编译器会将`INCLUDE_DIRS`中的目录忽略，继而在RefineDet当前目录下，寻找头文件. 

关于gcc 参数 `-isystem`, `-I` 的解释，参考[官方文档](https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html)

> If a standard system include directory, or a directory specified with -isystem, is also specified with -I, the -I option is ignored.

**Comment by sfzhang15** [comment]
@sdews 好的，由于没有make test的习惯，所以没注意到上面这个问题，非常感谢，makefile已更新。
