### ISSUE TITLE
Cudasuccess(10 vs 0)

### ISSUE THREAD

**Issue by jYaog** [sfzhang15/RefineDet#63]
I have only one GPU，so I set gpus="0" in finetune_VGG16_VOC2007_320.py ,but it still occur an error.How should I do? Thanks !

![qq 20180522171236](https://user-images.githubusercontent.com/23335057/40353137-52c8e2c2-5de3-11e8-9f57-36a97eea45d0.jpg)
![qq 20180522171202](https://user-images.githubusercontent.com/23335057/40353147-59ff73da-5de3-11e8-93b4-22d6f8610e91.jpg)

**Comment by sfzhang15** [comment]
@jYaog 
You can check the generated .sh file in jobs document whether the gpu ID is right.

**Comment by jYaog** [comment]
@sfzhang15 
I have solved the problem. Thanks
