### ISSUE TITLE
你好，我想问下可以发个整个网络的架构图吗

### ISSUE THREAD

**Issue by zq1314** [sfzhang15/RefineDet#65]
我的邮箱1908344230@qq.com @sfzhang15

**Comment by sfzhang15** [comment]
@zq1314 
所有训好的模型和prototxt已提供，你可以自己下载

**Comment by zq1314** [comment]
你好，我看论文时发现ODM是由TCB处理ARM中的anchor中的特征图得到，也就是说，ODM得到的不是整个特征图，这点我不能理解，希望楼主能解释下，谢谢。

**Comment by zq1314** [comment]
非常感谢你的回答，但是我还是有一些地方不明白。主要是对arm中整个特征卷积嘛，但是论文中说用tcb只是对anchor相关的部分卷积。

**Comment by sfzhang15** [comment]
@zq1314 
“on the feature maps associated with anchors”意思是检测层

**Comment by zq1314** [comment]
谢谢啦，现在终于明白了，感谢你的耐心回答！@sfzhang15
