### ISSUE TITLE
Results of ResNet101 on VOC2007

### ISSUE THREAD

**Issue by youngwanLEE** [sfzhang15/RefineDet#66]
Hi,

I trained RefineDet320/512-Res101 on VOC0712 and tested on VOC2007.

RefineDet320 : 79.77 | RefineDet512 : 82.91

What do think about these results? Did you train and test the RefineDet-ResNet101 on VOC ??

**Comment by junjieAI** [comment]
@youngwanLEE 
Hi,
How did you finish the train of RefineDet320/512-Res101 on VOC0712, and I got some problem, could you give some help? thanks

**Comment by sfzhang15** [comment]
@youngwanLEE 
Hi, we think this result is reasonable and promising, which is consistent with the results shown in DSSD Table 3, i.e., the mAP of SSD_321_ResNet101 is slightly lower than SSD_300_VGG and the mAP of SSD_513_ResNet101 is 1.1% higher than SSD_512_VGG. We think the reason that SSD_321_ResNet101 has worse performance than SSD_300_VGG may be that the stride 2 in the first conv of ResNet is harmful, especially for the small input size.

**Comment by youngwanLEE** [comment]
@sfzhang15 
Yes, I agree with your opinion. Can I cite these results in my paper? or If you get the better results, I want to cite your results.

**Comment by sfzhang15** [comment]
@youngwanLEE 
Yes, you can cite these results, marked training by yourselves, since we have not reported the results of ResNet101 on VOC.

**Comment by youngwanLEE** [comment]
@sfzhang15 thanks

**Comment by junjieAI** [comment]
@youngwanLEE 
I use 1080TiGPU and the Batch Size is 2(if bigger, will arise out of memory error), finally the mAP is much lower than VGG_512, so I'm wondering whether there are some mistakes during the process.

**Comment by sfzhang15** [comment]
@junjieAI 
Too few imags (＜5) per GPU will lead to unstable BN statistics.

**Comment by youngwanLEE** [comment]
@junjieAI 
I think so. DSSD paper said "A batch size smaller than 16 and trained on 4GPUs can cause unstable results in batch normalization and hurt accuracy". 
And I also this problem when using smaller than 4 per GPU.
