### ISSUE TITLE
I want to know the version of opencv you use.

### ISSUE THREAD

**Issue by miraclewkf** [sfzhang15/RefineDet#68]
Do you use opencv 3?

**Comment by sfzhang15** [comment]
@miraclewkf Hi,
We ues opencv 2.4.13

**Comment by miraclewkf** [comment]
I also do `# OPENCV_VERSION := 3` in Makefile.config, but when I run `make all -j`, I get this error:
```
collect2: error: ld returned 1 exit status
Makefile:619: recipe for target '.build_release/tools/upgrade_net_proto_binary.bin' failed
make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1
```

**Comment by miraclewkf** [comment]
@sfzhang15
So you set `# USE_OPENCV := 0` and `# OPENCV_VERSION := 3` in Makefile.config? Do you meet this error:
```
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: cannot find -lopencv_imgcodecs
collect2: error: ld returned 1 exit status
Makefile:566: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc3' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1
```

**Comment by sfzhang15** [comment]
@miraclewkf 
We set # USE_OPENCV := 0 and # OPENCV_VERSION := 3 in Makefile.config and do not meet this error. You can try to install opencv 2.4.13 from source.

**Comment by miraclewkf** [comment]
@sfzhang15 I fix this error through docker. Thanks.
