### ISSUE TITLE
Something about COCO dataset

### ISSUE THREAD

**Issue by Angzz** [sfzhang15/RefineDet#69]
Hi, I have successfully train and test with voc and my own dataset, and also successfully train with coco, but when I test with coco,  

I cant't find ``single_test_deploy.prototxt`` or ``multi_test_deploy.prototxt`` in refinedet_test.py, in fact I even don't know where to generate these files, because I only see the ``deploy.prototxt``, should I only change the ``deploy.prototxt`` will be OK? so can you give me some suggestions?

thanks!!!

**Comment by sfzhang15** [comment]
@Angzz Hi,
The single_test_deploy.prototxt and multi_test_deploy.prototxt are generated from deploy.prototxt, you can use comparison software (e.g., vimdiff and meld) to find the difference between single_test_deploy.prototxt and multi_test_deploy.prototxt, and then modify the deploy.prototxt correspondingly.

**Comment by Angzz** [comment]
@sfzhang15 that is to say, the ``single_test_deploy.prototxt`` and ``multi_test_deploy.prototxt`` are modified from ``deploy.prototxt``, but not generate from code, right?

**Comment by sfzhang15** [comment]
@Angzz Yes

**Comment by Angzz** [comment]
@sfzhang15 Thanks very much, I really appreciate  your help.
