### ISSUE TITLE
problem in  caffe's make  test,make runtest process

### ISSUE THREAD

**Issue by andyhx** [sfzhang15/RefineDet#7]
hi,sir:
  thank you for your great  job,when compling your caffe code ,it is ok  in make  -j
8 and make pycaffe process,  but some problems occured  in the make test  and runtest process ,it tells the following errors :  

-    .../RefineDet/src/caffe/test/test_bbox_util.cpp:757:59: error: no matching function for call to ?.etGroundTruth(float*&, const int&, int, bool, std::map<int, std::vector<caffe::NormalizedBBox> >*)?
   GetGroundTruth(gt_data, num_gt, -1, true, &all_gt_bboxes);
![image](https://user-images.githubusercontent.com/7508723/33108235-3b771946-cf76-11e7-958d-e086de809179.png)
do you know why ,how to fix it ,is it necessary to run make test  command or I can  skip it  ,have anyone successfully compiling the code,tell me ,thank u!

**Comment by sfzhang15** [comment]
@andyhx 
Hi, it is not necessary to run make test command and you can skip it.

**Comment by sfzhang15** [comment]
@andyhx 
We modify some layers and add some functions, but we do not modify the corresponding test file. So the make test and runtest process will tell the above error. Thanks for your report and we have modified the README.

**Comment by andyhx** [comment]
thanks
