### ISSUE TITLE
Is the model "RefineDet512+" totally same with "RefineDet512" in your paper?

### ISSUE THREAD

**Issue by xiaozhi2015** [sfzhang15/RefineDet#74]
What does "RefineDet512+" mean in your paper? You said that "To reduce the impact of input size for a
fair comparison, we use the multi-scale testing strategy to evaluate RefineDet". Is that means you use different input size img and if one of them gets the right result then the final right result add one? Is the model "RefineDet512+" totally same with "RefineDet512"?
Thx! @sfzhang15

**Comment by Angzz** [comment]
I think RefineDet512+ just mean use multi-scale testing strategy, nothing else different with RefinrDet512

**Comment by sfzhang15** [comment]
@xiaozhi2015 
As @Angzz said, the "RefineDet512+" is totally same with "RefineDet512". For the the multi-scale testing strategy, please refer to  [refinedet_test.py](https://github.com/sfzhang15/RefineDet/blob/master/test/refinedet_test.py).

**Comment by xiaozhi2015** [comment]
Thx a lot! @Angzz  @sfzhang15 
Do you know this guy "Junnan Zhu", who is majoring in NLP in your institute. My qq: 2574015660, hope to talk. ^_^
