### ISSUE TITLE
编译遇到来一些错误，请教一下楼主

### ISSUE THREAD

**Issue by loujt1984** [sfzhang15/RefineDet#75]
您好
  我用make all -j &&make py  进行编译时，遇到了下面一些错误，请指点迷津一下，谢谢！
src/caffe/layers/permute_layer.cpp:36:23: error: ‘permute_param’ was not declared in this scope
recipe for target '.build_release/src/caffe/layers/permute_layer.o' failed
src/caffe/layers/prior_box_layer.cpp:13:9: error: ‘PriorBoxParameter’ does not name a type
src/caffe/layers/prior_box_layer.cpp:15:12: error: ‘prior_box_param’ was not declared in this scope
./include/caffe/data_transformer.hpp:69:24: error: ‘AnnotatedDatum’ does not name a type
。。。。。。。

**Comment by sfzhang15** [comment]
@loujt1984 
请见这个[issue](https://github.com/sfzhang15/RefineDet/issues/60).
