### ISSUE TITLE
Something about multi_scale_test

### ISSUE THREAD

**Issue by Angzz** [sfzhang15/RefineDet#76]
Hi, when I change some architecture in ``AddExtraLayers`` function, the multi_scale_test doesn't works(single_scale_test is right), but when I change to the original RefineDet, it works as usual,so what is the most likely reason? I think the multi_scale_test strategy is general and isn't limited to specific architecture.

**Comment by sfzhang15** [comment]
@Angzz 
The multi_scale_test doesn't work and what is the error message?
