### ISSUE TITLE
the network  doesn't converge?

### ISSUE THREAD

**Issue by hlic** [sfzhang15/RefineDet#79]
are the LMDB data type of COCO and VOC the same ? why I use resnet101_coco_512.py to train VOC LMDB, the network  doesn't converge?? I use 3 TiTAN X， batchsize is 3 for one gpu。

**Comment by sfzhang15** [comment]
@hlic 
1. Their type are almost the same. Why do you not use resnet101_voc_512.py to train VOC LMDB?
2. batchsize 3 per GPU will result in unstable BN information.

**Comment by hlic** [comment]
@sfzhang15 Thanks for your reply! the  resnet101_coco_512.py  just can set batch size = 2 per GPU, and i just have 3 TITAN xp. If I want to train the network better, how can I do?

**Comment by sfzhang15** [comment]
@hlic 
You can try to fix the BN layer.
