### ISSUE TITLE
Loss 0 on both heads.

### ISSUE THREAD

**Issue by PetreanuAndi** [sfzhang15/RefineDet#87]
Hello. I'm trying to train your architecture on a different dataset, and I have two issues.

1) It seems like once every 100 iterations or so, there will be an accumulated loss of 0 on both arm and odm. That doesn't seem right, it can not be possible, over 10 iterations (display window) *batch_size to have 0 loss.
I have tried lowering the base_lr but I still get the same output in terms of loss. See attached picture.

2) Secondly, although the _training seems to work_, overall, and the loss decreases (from around 45 to around 7), at test time (single_scale) _the network performs extremely badly_, with mAP results of under 0.1 across all classes. 

The visualization of some inference examples shows that only medium-sized objects are detected (a sign that something was learned), but large / small objects are not, and there are a LOT of false positives in some images. This is after aprox. 20 epochs, 1 GPU, 2 batch_size, [832,512] input size. (I tried to keep the aspect ratio of a HD image 1280*720, while still dividing to 64, like SSD)

Any help/tips/tricks would be very much appreciated. 

![loss-0](https://user-images.githubusercontent.com/19908335/42569934-e3ef200a-851a-11e8-999e-8c9a2d5e65f4.png)

**Comment by sfzhang15** [comment]
@PetreanuAndi 
From these information, I can not know where is the problem. Since you train on your own dataset, you'd better to check every steps carefully, such as Imdb genetation.

**Comment by sfzhang15** [comment]
@PetreanuAndi 
OK. lmdb is right.
You should ensure that training and testing are consistent. If images of your dataset have a fixed resolution, you can train and test it with original size.

**Comment by laycoding** [comment]
@PetreanuAndi 
hi, i thought there is nothing wrong if your task is easy, you can try a larger batch_size

**Comment by PetreanuAndi** [comment]
Code suggests that prior box generation is based on fixed square aspect ratio. 
I tried training with a different resolution (and aspect ratio) and it does not seem to learn.
Results are inconsistent with paper findings, and i only changed dataset, sizes&box aspect ratios, rest of the code is default. ResNet 101 Faster RCNN gives me 84%, RefineDet 52% :(

**Comment by sfzhang15** [comment]
@PetreanuAndi 
Training for different dataset, there are many places that need to be modified. According to your description, I do not know the reason. You better analyze it yourself and see where the problem is.
