### ISSUE TITLE
The difference between VOC model and COCO model.

### ISSUE THREAD

**Issue by miraclewkf** [sfzhang15/RefineDet#88]
I want to know the difference between `models_VGGNet_VOC0712_refinedet_vgg16_320x320_coco.tar.gz` and `models_VGGNet_coco_refinedet_vgg16_320x320.tar.gz`. In my opinion, these two models are both train in COCO dataset from pretrain model VGGNet, is it right?

**Comment by sfzhang15** [comment]
The models_VGGNet_VOC0712_refinedet_vgg16_320x320_coco.tar.gz is directly converted from models_VGGNet_coco_refinedet_vgg16_320x320.tar.gz using [convert_model_320.ipynb](https://github.com/sfzhang15/RefineDet/blob/master/examples/convert_model_320.ipynb).
