### ISSUE TITLE
Error in VOC0712Plus/create_list.sh

### ISSUE THREAD

**Issue by reid3290** [sfzhang15/RefineDet#9]
When I run ```./data/VOC0712Plus/create_list.sh``` I got this error:
![image](https://user-images.githubusercontent.com/9301137/33194579-91547cfc-d096-11e7-9748-5aefbef11f8d.png)
```./data/VOC0712/create_list.sh``` and ```./data/VOC0712/create_data.sh``` is all good.

**Comment by sfzhang15** [comment]
@reid3290 Hi, you should download the VOC2012test.tar via http://host.robots.ox.ac.uk:8080/eval/downloads/VOC2012test.tar and upzip it. The README.md of VOC0712Plus will be updated. Thanks!
