### ISSUE TITLE
loss

### ISSUE THREAD

**Issue by 741077510** [sfzhang15/RefineDet#90]
Due to the limited gpus, i have only two 1080ti gpus so i change the batch_size and the accum_batch_size to 16. It seems that the loss is always 4.0+ since 8w iterations. Is it normal or should i change the learning rate? In SSD there is a solution that we can only change the batch_size to 16 but keep the accum_batch_size as 32, can you give me some advices whether it is right?

**Comment by sfzhang15** [comment]
@741077510 
I think it is normal. You can test it on VOC to check whether it is right.
