### ISSUE TITLE
question about FPS

### ISSUE THREAD

**Issue by HongyiDuanmu26** [sfzhang15/RefineDet#91]
Thank you for your great repo!
I have tried my own model for my task, two class detection problem. The FPS I got is about 2-3. It is tested in one K80 and the resolution of picture is 1280*720. Is it normal or what can I do to make it faster?
Thanks a lot!

**Comment by sfzhang15** [comment]
@HongyiDuanmu26 
With the input size 1280*720 on K80, the speed should be normal. The speed at our paper is tested on TTIAN X (Maxwell) with the input size 320*320 or 512*512.

**Comment by Google1234** [comment]
With the input size 512x512 ,Resnet101 framework on P100, the speed is 63ms/single image(use merged Batch Normalization) . Is it normal or what can I do to make it faster?
Thanks a lot !

**Comment by sfzhang15** [comment]
@Google1234 
For Resnet101_512x512, I think the speed 63ms is normal. If you want to make it faster, the best way may be use more lightweight backbone.

**Comment by HongyiDuanmu26** [comment]
Sorry for bothering you again. But may I ask if there are some techniques to make it faster like batch testing etc.?
Thank you so much in advance!

**Comment by sfzhang15** [comment]
@HongyiDuanmu26 
You can merge BN into conv and the best way may be use more lightweight backbone
