### ISSUE TITLE
Is the backbone weights frozen during training?

### ISSUE THREAD

**Issue by pobei** [sfzhang15/RefineDet#92]
hello, i am implement refindet by tensorflow. i find that the pool5 layer generate big output and the value from arm branch is very big correspond to the anchor index 6000--6300(10x10)feature map,  this often occurs after a few iterations. and then the output value from pool5 is almost zero and the network stop to learn, ..., i find the tensorflow version of ssd(https://github.com/balancap/SSD-Tensorflow), and notice that it freeze the backbone parameters at start and then carry the full training.

**Comment by sfzhang15** [comment]
@pobei 
Hi, we do not freeze the backbone parameters at start and so do the official SSD. Do you use the [normalization](https://github.com/sfzhang15/RefineDet/blob/master/include/caffe/layers/normalize_layer.hpp) opration?

**Comment by pobei** [comment]
the problem occurs even i add scaling(10 and 8) normalization to conv4_3 and conv5_3.  I think the init lr is huge, maybe the network need warm up.. and i am trying with it.

**Comment by sfzhang15** [comment]
@pobei 
I am not familiar with Tensorflow. If the tensorflow version of ssd freezes the backbone parameters at start and then carries the full training, you better do this too.

**Comment by pobei** [comment]
the performance of( https://github.com/balancap/SSD-Tensorflow) is not good, and warm up operation seems not work....

**Comment by sfzhang15** [comment]
@pobei 
You better implement RefineDet based on the proven tensorflow version of SSD.

**Comment by pobei** [comment]
thansk, i have solved the problem. the parameters of fc6 and fc7 are upsampled from vgg, and i just random initial them...

**Comment by YgRen** [comment]
@sfzhang15 hello, can you share the refinedet implement with tensorflow code?  thx!

**Comment by YgRen** [comment]
@pobei hello, can you share the refinedet implement with tensorflow code? thx!

**Comment by zslcodestorehouse** [comment]
> thansk, i have solved the problem. the parameters of fc6 and fc7 are upsampled from vgg, and i just random initial them...

Can you elaborate on how you solved this step? it would be better to have only one piece of code.thank you very much。
