### ISSUE TITLE
something about the time of training

### ISSUE THREAD

**Issue by junjieAI** [sfzhang15/RefineDet#93]
hi,
    Recently, I recommended your ideas to my friend, and he also trained with his own data, both of us use the same parameters, such as: batch_size, and the same GPU1080Ti. while the problem is that his iteration reaches 70 thousands one day, and mines is about to 15 thousands with a huge difference.
    So, I want to make sure whether my training exists problems or the exactly iteration should be? thanks

**Comment by sfzhang15** [comment]
@junjieAI 
For RefineDet320_VGG16, we use 4 TITAN X (Maxwell) GPUs and every GPU has 8 images, so the total batch size is 32. Every iteration takes 1.4s and we train it 12K, so we need about 27 hours to finish the training.

**Comment by junjieAI** [comment]
@sfzhang15 
ok, thanks
