### ISSUE TITLE
question about the box regression of refined box in odm phase 

### ISSUE THREAD

**Issue by xinghedyc** [sfzhang15/RefineDet#95]
Hi thanks for your inspiring work.
But I have a question about:
You said "ARM regresses from anchor to GT, while ODM regresses from the regression results of ARM to GT to get better localization"
 However, I don't find the regression inputs  in odm phase when doing box regression, Only can I find the arm loc preds are in the loss calculation process. Does it mean that in the odm phase the default prior boxes are replaced by the arm_loc_preds?  But odm regression process is the same as arm (convolution layer)?

**Comment by sfzhang15** [comment]
@xinghedyc 
At [here](https://github.com/sfzhang15/RefineDet/blob/master/src/caffe/util/bbox_util.cpp#L811-L813), we will apply arm_loc_pred to the default prior boxes to get the refined prior boxes, then do match process. ODM regression process is the same as ARM, but with the refined prior boxes.

**Comment by xinghedyc** [comment]
Thanks for your reply.
But I have a another question: the refined prior boxes are generated differently among different images, does it make the regression too hard to learn compared to using fixed default boxes?

**Comment by sfzhang15** [comment]
@xinghedyc 
The refined prior boxes are generated according to the output of ARM, which can provide better regression start point for different image. It is better than regressing from the defaulted prior boxes. Our results and CascadeR-CNN can prove it.

**Comment by Google1234** [comment]
mean ARM and ODM use the same **feature area** in different feature map?

**Comment by Google1234** [comment]
@sfzhang15
mean ARM and ODM use the same feature area in different feature map?

**Comment by xinghedyc** [comment]
I'm confused about that when you do box regression in odm phase, you don't actually know the results of arm_loc_preds because the arm_loc_preds are not the inputs of odm regression branch, so the regression of odm actually dose't know where to start to regress. In the arm phase the regression starts from fixed prior boxes but in odm phase the regression starts  from unfixed refined boxes, am I right?

**Comment by sfzhang15** [comment]
@Google1234 
Yes

**Comment by Google1234** [comment]
@sfzhang15 
THX～

**Comment by Google1234** [comment]
@xinghedyc 
see  [here](https://github.com/sfzhang15/RefineDet/blob/78c3701afc9d5b927b3c7b366ae33c5bbb8dbe2c/src/caffe/layers/multibox_loss_layer.cpp#L182)
