### ISSUE TITLE
fail to make all  

### ISSUE THREAD

**Issue by Arthur-Shi** [sfzhang15/RefineDet#96]
./include/caffe/util/bbox_util.hpp:30:25: error: ‘NormalizedBBox’ was not declared in this scope
 typedef map<int, vector<NormalizedBBox> > LabelBBox;
                         ^
./include/caffe/util/bbox_util.hpp:30:39: error: template argument 1 is invalid
 typedef map<int, vector<NormalizedBBox> > LabelBBox;
                                       ^
./include/caffe/util/bbox_util.hpp:30:39: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:30:41: error: template argument 2 is invalid
 typedef map<int, vector<NormalizedBBox> > LabelBBox;
                                         ^
./include/caffe/util/bbox_util.hpp:30:41: error: template argument 4 is invalid
./include/caffe/util/bbox_util.hpp:34:27: error: ‘NormalizedBBox’ does not name a type
 bool SortBBoxAscend(const NormalizedBBox& bbox1, const NormalizedBBox& bbox2);
                           ^
./include/caffe/util/bbox_util.hpp:34:56: error: ‘NormalizedBBox’ does not name a type
 bool SortBBoxAscend(const NormalizedBBox& bbox1, const NormalizedBBox& bbox2);
                                                        ^
./include/caffe/util/bbox_util.hpp:38:28: error: ‘NormalizedBBox’ does not name a type
 bool SortBBoxDescend(const NormalizedBBox& bbox1, const NormalizedBBox& bbox2);
                            ^
./include/caffe/util/bbox_util.hpp:38:57: error: ‘NormalizedBBox’ does not name a type
 bool SortBBoxDescend(const NormalizedBBox& bbox1, const NormalizedBBox& bbox2);
                                                         ^
./include/caffe/util/bbox_util.hpp:53:1: error: ‘NormalizedBBox’ does not name a type
 NormalizedBBox UnitBBox();
 ^
./include/caffe/util/bbox_util.hpp:56:32: error: ‘NormalizedBBox’ does not name a type
 bool IsCrossBoundaryBBox(const NormalizedBBox& bbox);
                                ^
./include/caffe/util/bbox_util.hpp:59:26: error: ‘NormalizedBBox’ does not name a type
 void IntersectBBox(const NormalizedBBox& bbox1, const NormalizedBBox& bbox2,
                          ^
./include/caffe/util/bbox_util.hpp:59:55: error: ‘NormalizedBBox’ does not name a type
 void IntersectBBox(const NormalizedBBox& bbox1, const NormalizedBBox& bbox2,
                                                       ^
./include/caffe/util/bbox_util.hpp:60:20: error: ‘NormalizedBBox’ has not been declared
                    NormalizedBBox* intersect_bbox);
                    ^
./include/caffe/util/bbox_util.hpp:63:22: error: ‘NormalizedBBox’ does not name a type
 float BBoxSize(const NormalizedBBox& bbox, const bool normalized = true);
                      ^
./include/caffe/util/bbox_util.hpp:69:21: error: ‘NormalizedBBox’ does not name a type
 void ClipBBox(const NormalizedBBox& bbox, NormalizedBBox* clip_bbox);
                     ^
./include/caffe/util/bbox_util.hpp:69:43: error: ‘NormalizedBBox’ has not been declared
 void ClipBBox(const NormalizedBBox& bbox, NormalizedBBox* clip_bbox);
                                           ^
./include/caffe/util/bbox_util.hpp:72:21: error: ‘NormalizedBBox’ does not name a type
 void ClipBBox(const NormalizedBBox& bbox, const float height, const float width,
                     ^
./include/caffe/util/bbox_util.hpp:73:15: error: ‘NormalizedBBox’ has not been declared
               NormalizedBBox* clip_bbox);
               ^
./include/caffe/util/bbox_util.hpp:76:22: error: ‘NormalizedBBox’ does not name a type
 void ScaleBBox(const NormalizedBBox& bbox, const int height, const int width,
                      ^
./include/caffe/util/bbox_util.hpp:77:16: error: ‘NormalizedBBox’ has not been declared
                NormalizedBBox* scale_bbox);
                ^
./include/caffe/util/bbox_util.hpp:80:23: error: ‘NormalizedBBox’ does not name a type
 void OutputBBox(const NormalizedBBox& bbox, const pair<int, int>& img_size,
                       ^
./include/caffe/util/bbox_util.hpp:81:46: error: ‘ResizeParameter’ does not name a type
                 const bool has_resize, const ResizeParameter& resize_param,
                                              ^
./include/caffe/util/bbox_util.hpp:82:17: error: ‘NormalizedBBox’ has not been declared
                 NormalizedBBox* out_bbox);
                 ^
./include/caffe/util/bbox_util.hpp:85:23: error: ‘NormalizedBBox’ does not name a type
 void LocateBBox(const NormalizedBBox& src_bbox, const NormalizedBBox& bbox,
                       ^
./include/caffe/util/bbox_util.hpp:85:55: error: ‘NormalizedBBox’ does not name a type
 void LocateBBox(const NormalizedBBox& src_bbox, const NormalizedBBox& bbox,
                                                       ^
./include/caffe/util/bbox_util.hpp:86:17: error: ‘NormalizedBBox’ has not been declared
                 NormalizedBBox* loc_bbox);
                 ^
./include/caffe/util/bbox_util.hpp:89:24: error: ‘NormalizedBBox’ does not name a type
 bool ProjectBBox(const NormalizedBBox& src_bbox, const NormalizedBBox& bbox,
                        ^
./include/caffe/util/bbox_util.hpp:89:56: error: ‘NormalizedBBox’ does not name a type
 bool ProjectBBox(const NormalizedBBox& src_bbox, const NormalizedBBox& bbox,
                                                        ^
./include/caffe/util/bbox_util.hpp:90:18: error: ‘NormalizedBBox’ has not been declared
                  NormalizedBBox* proj_bbox);
                  ^
./include/caffe/util/bbox_util.hpp:94:28: error: ‘ResizeParameter’ does not name a type
 void ExtrapolateBBox(const ResizeParameter& param, const int height,
                            ^
./include/caffe/util/bbox_util.hpp:95:28: error: ‘NormalizedBBox’ does not name a type
     const int width, const NormalizedBBox& crop_bbox, NormalizedBBox* bbox);
                            ^
./include/caffe/util/bbox_util.hpp:95:55: error: ‘NormalizedBBox’ has not been declared
     const int width, const NormalizedBBox& crop_bbox, NormalizedBBox* bbox);
                                                       ^
./include/caffe/util/bbox_util.hpp:98:28: error: ‘NormalizedBBox’ does not name a type
 float JaccardOverlap(const NormalizedBBox& bbox1, const NormalizedBBox& bbox2,
                            ^
./include/caffe/util/bbox_util.hpp:98:57: error: ‘NormalizedBBox’ does not name a type
 float JaccardOverlap(const NormalizedBBox& bbox1, const NormalizedBBox& bbox2,
                                                         ^
./include/caffe/util/bbox_util.hpp:105:26: error: ‘NormalizedBBox’ does not name a type
 float BBoxCoverage(const NormalizedBBox& bbox1, const NormalizedBBox& bbox2);
                          ^
./include/caffe/util/bbox_util.hpp:105:55: error: ‘NormalizedBBox’ does not name a type
 float BBoxCoverage(const NormalizedBBox& bbox1, const NormalizedBBox& bbox2);
                                                       ^
./include/caffe/util/bbox_util.hpp:108:23: error: ‘NormalizedBBox’ does not name a type
 void EncodeBBox(const NormalizedBBox& prior_bbox,
                       ^
./include/caffe/util/bbox_util.hpp:109:48: error: ‘CodeType’ does not name a type
     const vector<float>& prior_variance, const CodeType code_type,
                                                ^
./include/caffe/util/bbox_util.hpp:110:49: error: ‘NormalizedBBox’ does not name a type
     const bool encode_variance_in_target, const NormalizedBBox& bbox,
                                                 ^
./include/caffe/util/bbox_util.hpp:111:5: error: ‘NormalizedBBox’ has not been declared
     NormalizedBBox* encode_bbox);
     ^
./include/caffe/util/bbox_util.hpp:114:31: error: ‘NormalizedBBox’ does not name a type
 bool MeetEmitConstraint(const NormalizedBBox& src_bbox,
                               ^
./include/caffe/util/bbox_util.hpp:115:11: error: ‘NormalizedBBox’ does not name a type
     const NormalizedBBox& bbox, const EmitConstraint& emit_constraint);
           ^
./include/caffe/util/bbox_util.hpp:115:39: error: ‘EmitConstraint’ does not name a type
     const NormalizedBBox& bbox, const EmitConstraint& emit_constraint);
                                       ^
./include/caffe/util/bbox_util.hpp:118:23: error: ‘NormalizedBBox’ does not name a type
 void DecodeBBox(const NormalizedBBox& prior_bbox,
                       ^
./include/caffe/util/bbox_util.hpp:119:48: error: ‘CodeType’ does not name a type
     const vector<float>& prior_variance, const CodeType code_type,
                                                ^
./include/caffe/util/bbox_util.hpp:121:11: error: ‘NormalizedBBox’ does not name a type
     const NormalizedBBox& bbox, NormalizedBBox* decode_bbox);
           ^
./include/caffe/util/bbox_util.hpp:121:33: error: ‘NormalizedBBox’ has not been declared
     const NormalizedBBox& bbox, NormalizedBBox* decode_bbox);
                                 ^
./include/caffe/util/bbox_util.hpp:124:32: error: ‘NormalizedBBox’ was not declared in this scope
 void DecodeBBoxes(const vector<NormalizedBBox>& prior_bboxes,
                                ^
./include/caffe/util/bbox_util.hpp:124:46: error: template argument 1 is invalid
 void DecodeBBoxes(const vector<NormalizedBBox>& prior_bboxes,
                                              ^
./include/caffe/util/bbox_util.hpp:124:46: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:126:11: error: ‘CodeType’ does not name a type
     const CodeType code_type, const bool variance_encoded_in_target,
           ^
./include/caffe/util/bbox_util.hpp:127:40: error: ‘NormalizedBBox’ was not declared in this scope
     const bool clip_bbox, const vector<NormalizedBBox>& bboxes,
                                        ^
./include/caffe/util/bbox_util.hpp:127:54: error: template argument 1 is invalid
     const bool clip_bbox, const vector<NormalizedBBox>& bboxes,
                                                      ^
./include/caffe/util/bbox_util.hpp:127:54: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:128:12: error: ‘NormalizedBBox’ was not declared in this scope
     vector<NormalizedBBox>* decode_bboxes);
            ^
./include/caffe/util/bbox_util.hpp:128:26: error: template argument 1 is invalid
     vector<NormalizedBBox>* decode_bboxes);
                          ^
./include/caffe/util/bbox_util.hpp:128:26: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:132:18: error: ‘NormalizedBBox’ was not declared in this scope
     const vector<NormalizedBBox>& prior_bboxes,
                  ^
./include/caffe/util/bbox_util.hpp:132:32: error: template argument 1 is invalid
     const vector<NormalizedBBox>& prior_bboxes,
                                ^
./include/caffe/util/bbox_util.hpp:132:32: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:136:11: error: ‘CodeType’ does not name a type
     const CodeType code_type, const bool variance_encoded_in_target,
           ^
./include/caffe/util/bbox_util.hpp:140:18: error: ‘NormalizedBBox’ was not declared in this scope
     const vector<NormalizedBBox>& prior_bboxes,
                  ^
./include/caffe/util/bbox_util.hpp:140:32: error: template argument 1 is invalid
     const vector<NormalizedBBox>& prior_bboxes,
                                ^
./include/caffe/util/bbox_util.hpp:140:32: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:144:11: error: ‘CodeType’ does not name a type
     const CodeType code_type, const bool variance_encoded_in_target,
           ^
./include/caffe/util/bbox_util.hpp:149:29: error: ‘NormalizedBBox’ was not declared in this scope
 void MatchBBox(const vector<NormalizedBBox>& gt,
                             ^
./include/caffe/util/bbox_util.hpp:149:43: error: template argument 1 is invalid
 void MatchBBox(const vector<NormalizedBBox>& gt,
                                           ^
./include/caffe/util/bbox_util.hpp:149:43: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:150:18: error: ‘NormalizedBBox’ was not declared in this scope
     const vector<NormalizedBBox>& pred_bboxes, const int label,
                  ^
./include/caffe/util/bbox_util.hpp:150:32: error: template argument 1 is invalid
     const vector<NormalizedBBox>& pred_bboxes, const int label,
                                ^
./include/caffe/util/bbox_util.hpp:150:32: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:151:11: error: ‘MatchType’ does not name a type
     const MatchType match_type, const float overlap_threshold,
           ^
./include/caffe/util/bbox_util.hpp:165:29: error: ‘NormalizedBBox’ was not declared in this scope
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                             ^
./include/caffe/util/bbox_util.hpp:165:43: error: template argument 1 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                           ^
./include/caffe/util/bbox_util.hpp:165:43: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:165:45: error: template argument 2 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                             ^
./include/caffe/util/bbox_util.hpp:165:45: error: template argument 4 is invalid
./include/caffe/util/bbox_util.hpp:166:20: error: ‘NormalizedBBox’ was not declared in this scope
       const vector<NormalizedBBox>& prior_bboxes,
                    ^
./include/caffe/util/bbox_util.hpp:166:34: error: template argument 1 is invalid
       const vector<NormalizedBBox>& prior_bboxes,
                                  ^
./include/caffe/util/bbox_util.hpp:166:34: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:168:13: error: ‘MultiBoxLossParameter’ does not name a type
       const MultiBoxLossParameter& multibox_loss_param,
             ^
./include/caffe/util/bbox_util.hpp:173:29: error: ‘NormalizedBBox’ was not declared in this scope
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                             ^
./include/caffe/util/bbox_util.hpp:173:43: error: template argument 1 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                           ^
./include/caffe/util/bbox_util.hpp:173:43: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:173:45: error: template argument 2 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                             ^
./include/caffe/util/bbox_util.hpp:173:45: error: template argument 4 is invalid
./include/caffe/util/bbox_util.hpp:174:20: error: ‘NormalizedBBox’ was not declared in this scope
       const vector<NormalizedBBox>& prior_bboxes,
                    ^
./include/caffe/util/bbox_util.hpp:174:34: error: template argument 1 is invalid
       const vector<NormalizedBBox>& prior_bboxes,
                                  ^
./include/caffe/util/bbox_util.hpp:174:34: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:176:13: error: ‘MultiBoxLossParameter’ does not name a type
       const MultiBoxLossParameter& multibox_loss_param,
             ^
./include/caffe/util/bbox_util.hpp:199:27: error: ‘NormalizedBBox’ was not declared in this scope
     const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                           ^
./include/caffe/util/bbox_util.hpp:199:41: error: template argument 1 is invalid
     const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                         ^
./include/caffe/util/bbox_util.hpp:199:41: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:199:43: error: template argument 2 is invalid
     const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                           ^
./include/caffe/util/bbox_util.hpp:199:43: error: template argument 4 is invalid
./include/caffe/util/bbox_util.hpp:200:18: error: ‘NormalizedBBox’ was not declared in this scope
     const vector<NormalizedBBox>& prior_bboxes,
                  ^
./include/caffe/util/bbox_util.hpp:200:32: error: template argument 1 is invalid
     const vector<NormalizedBBox>& prior_bboxes,
                                ^
./include/caffe/util/bbox_util.hpp:200:32: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:203:11: error: ‘MultiBoxLossParameter’ does not name a type
     const MultiBoxLossParameter& multibox_loss_param,
           ^
./include/caffe/util/bbox_util.hpp:219:23: error: ‘NormalizedBBox’ was not declared in this scope
       map<int, vector<NormalizedBBox> >* all_gt_bboxes);
                       ^
./include/caffe/util/bbox_util.hpp:219:37: error: template argument 1 is invalid
       map<int, vector<NormalizedBBox> >* all_gt_bboxes);
                                     ^
./include/caffe/util/bbox_util.hpp:219:37: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:219:39: error: template argument 2 is invalid
       map<int, vector<NormalizedBBox> >* all_gt_bboxes);
                                       ^
./include/caffe/util/bbox_util.hpp:219:39: error: template argument 4 is invalid
./include/caffe/util/bbox_util.hpp:252:29: error: ‘NormalizedBBox’ was not declared in this scope
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                             ^
./include/caffe/util/bbox_util.hpp:252:43: error: template argument 1 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                           ^
./include/caffe/util/bbox_util.hpp:252:43: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:252:45: error: template argument 2 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                             ^
./include/caffe/util/bbox_util.hpp:252:45: error: template argument 4 is invalid
./include/caffe/util/bbox_util.hpp:254:20: error: ‘NormalizedBBox’ was not declared in this scope
       const vector<NormalizedBBox>& prior_bboxes,
                    ^
./include/caffe/util/bbox_util.hpp:254:34: error: template argument 1 is invalid
       const vector<NormalizedBBox>& prior_bboxes,
                                  ^
./include/caffe/util/bbox_util.hpp:254:34: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:256:13: error: ‘MultiBoxLossParameter’ does not name a type
       const MultiBoxLossParameter& multibox_loss_param,
             ^
./include/caffe/util/bbox_util.hpp:261:29: error: ‘NormalizedBBox’ was not declared in this scope
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                             ^
./include/caffe/util/bbox_util.hpp:261:43: error: template argument 1 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                           ^
./include/caffe/util/bbox_util.hpp:261:43: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:261:45: error: template argument 2 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                             ^
./include/caffe/util/bbox_util.hpp:261:45: error: template argument 4 is invalid
./include/caffe/util/bbox_util.hpp:263:20: error: ‘NormalizedBBox’ was not declared in this scope
       const vector<NormalizedBBox>& prior_bboxes,
                    ^
./include/caffe/util/bbox_util.hpp:263:34: error: template argument 1 is invalid
       const vector<NormalizedBBox>& prior_bboxes,
                                  ^
./include/caffe/util/bbox_util.hpp:263:34: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:265:13: error: ‘MultiBoxLossParameter’ does not name a type
       const MultiBoxLossParameter& multibox_loss_param,
             ^
./include/caffe/util/bbox_util.hpp:280:50: error: ‘LocLossType’ does not name a type
       const int num, const int num_priors, const LocLossType loc_loss_type,
                                                  ^
./include/caffe/util/bbox_util.hpp:329:44: error: ‘ConfLossType’ does not name a type
       const int background_label_id, const ConfLossType loss_type,
                                            ^
./include/caffe/util/bbox_util.hpp:331:29: error: ‘NormalizedBBox’ was not declared in this scope
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                             ^
./include/caffe/util/bbox_util.hpp:331:43: error: template argument 1 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                           ^
./include/caffe/util/bbox_util.hpp:331:43: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:331:45: error: template argument 2 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                             ^
./include/caffe/util/bbox_util.hpp:331:45: error: template argument 4 is invalid
./include/caffe/util/bbox_util.hpp:346:44: error: ‘ConfLossType’ does not name a type
       const int background_label_id, const ConfLossType loss_type,
                                            ^
./include/caffe/util/bbox_util.hpp:361:35: error: ‘MultiBoxLossParameter’ does not name a type
       const int num_priors, const MultiBoxLossParameter& multibox_loss_param,
                                   ^
./include/caffe/util/bbox_util.hpp:364:29: error: ‘NormalizedBBox’ was not declared in this scope
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                             ^
./include/caffe/util/bbox_util.hpp:364:43: error: template argument 1 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                           ^
./include/caffe/util/bbox_util.hpp:364:43: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:364:45: error: template argument 2 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                             ^
./include/caffe/util/bbox_util.hpp:364:45: error: template argument 4 is invalid
./include/caffe/util/bbox_util.hpp:374:14: error: ‘NormalizedBBox’ was not declared in this scope
       vector<NormalizedBBox>* prior_bboxes,
              ^
./include/caffe/util/bbox_util.hpp:374:28: error: template argument 1 is invalid
       vector<NormalizedBBox>* prior_bboxes,
                            ^
./include/caffe/util/bbox_util.hpp:374:28: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:432:28: error: ‘NormalizedBBox’ was not declared in this scope
 void ApplyNMS(const vector<NormalizedBBox>& bboxes, const vector<float>& scores,
                            ^
./include/caffe/util/bbox_util.hpp:432:42: error: template argument 1 is invalid
 void ApplyNMS(const vector<NormalizedBBox>& bboxes, const vector<float>& scores,
                                          ^
./include/caffe/util/bbox_util.hpp:432:42: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:436:28: error: ‘NormalizedBBox’ was not declared in this scope
 void ApplyNMS(const vector<NormalizedBBox>& bboxes, const vector<float>& scores,
                            ^
./include/caffe/util/bbox_util.hpp:436:42: error: template argument 1 is invalid
 void ApplyNMS(const vector<NormalizedBBox>& bboxes, const vector<float>& scores,
                                          ^
./include/caffe/util/bbox_util.hpp:436:42: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:451:32: error: ‘NormalizedBBox’ was not declared in this scope
 void ApplyNMSFast(const vector<NormalizedBBox>& bboxes,
                                ^
./include/caffe/util/bbox_util.hpp:451:46: error: template argument 1 is invalid
 void ApplyNMSFast(const vector<NormalizedBBox>& bboxes,
                                              ^
./include/caffe/util/bbox_util.hpp:451:46: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:503:17: error: ‘CodeType’ does not name a type
           const CodeType code_type, const bool variance_encoded_in_target,
                 ^
./include/caffe/util/bbox_util.hpp:511:17: error: ‘CodeType’ does not name a type
           const CodeType code_type, const bool variance_encoded_in_target,
                 ^
./include/caffe/util/bbox_util.hpp:553:44: error: ‘ConfLossType’ does not name a type
       const int background_label_id, const ConfLossType loss_type,
                                            ^
./include/caffe/util/bbox_util.hpp:555:29: error: ‘NormalizedBBox’ was not declared in this scope
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                             ^
./include/caffe/util/bbox_util.hpp:555:43: error: template argument 1 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                           ^
./include/caffe/util/bbox_util.hpp:555:43: error: template argument 2 is invalid
./include/caffe/util/bbox_util.hpp:555:45: error: template argument 2 is invalid
       const map<int, vector<NormalizedBBox> >& all_gt_bboxes,
                                             ^
./include/caffe/util/bbox_util.hpp:555:45: error: template argument 4 is invalid
In file included from src/caffe/layers/multibox_loss_layer.cpp:6:0:
./include/caffe/layers/multibox_loss_layer.hpp:51:3: error: ‘LocLossType’ does not name a type
   LocLossType loc_loss_type_;
   ^
./include/caffe/layers/multibox_loss_layer.hpp:66:3: error: ‘ConfLossType’ does not name a type
   ConfLossType conf_loss_type_;
   ^
./include/caffe/layers/multibox_loss_layer.hpp:78:3: error: ‘MultiBoxLossParameter’ does not name a type
   MultiBoxLossParameter multibox_loss_param_;
   ^
./include/caffe/layers/multibox_loss_layer.hpp:81:3: error: ‘MatchType’ does not name a type
   MatchType match_type_;
   ^
./include/caffe/layers/multibox_loss_layer.hpp:89:3: error: ‘CodeType’ does not name a type
   CodeType code_type_;
   ^
./include/caffe/layers/multibox_loss_layer.hpp:94:3: error: ‘MiningType’ does not name a type
   MiningType mining_type_;
   ^
src/caffe/layers/multibox_loss_layer.cpp: In member function ‘virtual void caffe::MultiBoxLossLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’:
src/caffe/layers/multibox_loss_layer.cpp:21:9: error: ‘MultiBoxLossParameter’ does not name a type
   const MultiBoxLossParameter& multibox_loss_param =
         ^
src/caffe/layers/multibox_loss_layer.cpp:23:3: error: ‘multibox_loss_param_’ was not declared in this scope
   multibox_loss_param_ = this->layer_param_.multibox_loss_param();
   ^
In file included from ./include/caffe/common.hpp:6:0,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/layers/multibox_loss_layer.hpp:8,
                 from src/caffe/layers/multibox_loss_layer.cpp:6:
src/caffe/layers/multibox_loss_layer.cpp:28:9: error: ‘multibox_loss_param’ was not declared in this scope
   CHECK(multibox_loss_param.has_num_classes()) << "Must provide num_classes.";
         ^
src/caffe/layers/multibox_loss_layer.cpp:35:3: error: ‘mining_type_’ was not declared in this scope
   mining_type_ = multibox_loss_param.mining_type();
   ^
In file included from ./include/caffe/common.hpp:6:0,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/layers/multibox_loss_layer.hpp:8,
                 from src/caffe/layers/multibox_loss_layer.cpp:6:
src/caffe/layers/multibox_loss_layer.cpp:40:30: error: ‘MultiBoxLossParameter_MiningType_NONE’ was not declared in this scope
              mining_type_ != MultiBoxLossParameter_MiningType_NONE);
                              ^
src/caffe/layers/multibox_loss_layer.cpp:42:36: error: ‘MultiBoxLossParameter_MiningType_NONE’ was not declared in this scope
   do_neg_mining_ = mining_type_ != MultiBoxLossParameter_MiningType_NONE;
                                    ^
src/caffe/layers/multibox_loss_layer.cpp:61:3: error: ‘loc_loss_type_’ was not declared in this scope
   loc_loss_type_ = multibox_loss_param.loc_loss_type();
   ^
src/caffe/layers/multibox_loss_layer.cpp:71:25: error: ‘MultiBoxLossParameter_LocLossType_L2’ was not declared in this scope
   if (loc_loss_type_ == MultiBoxLossParameter_LocLossType_L2) {
                         ^
src/caffe/layers/multibox_loss_layer.cpp:78:32: error: ‘MultiBoxLossParameter_LocLossType_SMOOTH_L1’ was not declared in this scope
   } else if (loc_loss_type_ == MultiBoxLossParameter_LocLossType_SMOOTH_L1) {
                                ^
src/caffe/layers/multibox_loss_layer.cpp:89:3: error: ‘conf_loss_type_’ was not declared in this scope
   conf_loss_type_ = multibox_loss_param.conf_loss_type();
   ^
src/caffe/layers/multibox_loss_layer.cpp:94:26: error: ‘MultiBoxLossParameter_ConfLossType_SOFTMAX’ was not declared in this scope
   if (conf_loss_type_ == MultiBoxLossParameter_ConfLossType_SOFTMAX) {
                          ^
src/caffe/layers/multibox_loss_layer.cpp:114:33: error: ‘MultiBoxLossParameter_ConfLossType_LOGISTIC’ was not declared in this scope
   } else if (conf_loss_type_ == MultiBoxLossParameter_ConfLossType_LOGISTIC) {
                                 ^
src/caffe/layers/multibox_loss_layer.cpp: In member function ‘virtual void caffe::MultiBoxLossLayer<Dtype>::Forward_cpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’:
src/caffe/layers/multibox_loss_layer.cpp:165:19: error: ‘NormalizedBBox’ was not declared in this scope
   map<int, vector<NormalizedBBox> > all_gt_bboxes;
                   ^
src/caffe/layers/multibox_loss_layer.cpp:165:33: error: template argument 1 is invalid
   map<int, vector<NormalizedBBox> > all_gt_bboxes;
                                 ^
src/caffe/layers/multibox_loss_layer.cpp:165:33: error: template argument 2 is invalid
src/caffe/layers/multibox_loss_layer.cpp:165:35: error: template argument 2 is invalid
   map<int, vector<NormalizedBBox> > all_gt_bboxes;
                                   ^
src/caffe/layers/multibox_loss_layer.cpp:165:35: error: template argument 4 is invalid
src/caffe/layers/multibox_loss_layer.cpp:171:24: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Alloc> class std::vector’
   vector<NormalizedBBox> prior_bboxes;
                        ^
src/caffe/layers/multibox_loss_layer.cpp:171:24: note:   expected a type, got ‘NormalizedBBox’
src/caffe/layers/multibox_loss_layer.cpp:171:24: error: template argument 2 is invalid
src/caffe/layers/multibox_loss_layer.cpp:184:8: error: ‘multibox_loss_param_’ was not declared in this scope
        multibox_loss_param_, &all_match_overlaps, &all_match_indices_, all_arm_loc_preds);
        ^
src/caffe/layers/multibox_loss_layer.cpp:188:17: error: ‘multibox_loss_param_’ was not declared in this scope
                 multibox_loss_param_, &all_match_overlaps, &all_match_indices_);
                 ^
src/caffe/layers/multibox_loss_layer.cpp:195:57: error: ‘multibox_loss_param_’ was not declared in this scope
                    prior_variances, all_match_overlaps, multibox_loss_param_,
                                                         ^
src/caffe/layers/multibox_loss_layer.cpp:233:9: error: ‘conf_loss_type_’ was not declared in this scope
     if (conf_loss_type_ == MultiBoxLossParameter_ConfLossType_SOFTMAX) {
         ^
src/caffe/layers/multibox_loss_layer.cpp:233:28: error: ‘MultiBoxLossParameter_ConfLossType_SOFTMAX’ was not declared in this scope
     if (conf_loss_type_ == MultiBoxLossParameter_ConfLossType_SOFTMAX) {
                            ^
src/caffe/layers/multibox_loss_layer.cpp:238:35: error: ‘MultiBoxLossParameter_ConfLossType_LOGISTIC’ was not declared in this scope
     } else if (conf_loss_type_ == MultiBoxLossParameter_ConfLossType_LOGISTIC) {
                                   ^
src/caffe/layers/multibox_loss_layer.cpp: In instantiation of ‘void caffe::MultiBoxLossLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/multibox_loss_layer.cpp:396:1:   required from here
src/caffe/layers/multibox_loss_layer.cpp:23:24: error: ‘class caffe::LayerParameter’ has no member named ‘multibox_loss_param’
   multibox_loss_param_ = this->layer_param_.multibox_loss_param();
                        ^
src/caffe/layers/multibox_loss_layer.cpp: In instantiation of ‘void caffe::MultiBoxLossLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/multibox_loss_layer.cpp:396:1:   required from here
src/caffe/layers/multibox_loss_layer.cpp:23:24: error: ‘class caffe::LayerParameter’ has no member named ‘multibox_loss_param’
make: *** [.build_release/src/caffe/layers/detection_evaluate_layer.o] 错误 1
make: *** [.build_release/src/caffe/layers/multibox_loss_layer.o] 错误 1

I tried many solutions, but still cannot work.

I tried 
	LIBRARIES += boost_thread stdc++ boost_regex
and 
sudo gedit /usr/include/boost/property_tree/detail/json_parser_read.hpp

/*escape
                    =   chset_p(detail::widen<Ch>("\"\\/bfnrt").c_str())
                            [typename Context::a_escape(self.c)]
                    |   'u' >> uint_parser<unsigned long, 16, 4, 4>()
                            [typename Context::a_unicode(self.c)]
                    ;*/

g++ 5.5.0
ubtuntu.14.04
cuda 8.0
cudnn 7.0.5

How can I make successfully？

**Comment by sfzhang15** [comment]
@Arthur-Shi 
Are you installing caffe2? Need to change the name of /usr/local/include/caffe folder, otherwise it will find this proto when compiling.

**Comment by Arthur-Shi** [comment]
yes, I did sudo mv former_name/ new_name/
 then it works.
Thank you so much
