### ISSUE TITLE
Trianing with my own dataset

### ISSUE THREAD

**Issue by Arthur-Shi** [sfzhang15/RefineDet#97]
I followed the README.md, and I can train VOC2007 dataset successfully. And then I met the problem.

I think it is not the memory problem. And my number of labels is two including background.

I0726 10:47:40.833505 23021 caffe.cpp:251] Starting Optimization
I0726 10:47:40.833554 23021 solver.cpp:294] Solving VOC0712_refinedet_vgg16_320x320_train
I0726 10:47:40.833562 23021 solver.cpp:295] Learning Rate Policy: multistep
F0726 10:47:40.858794 23021 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7ff8422a8daa  (unknown)
    @     0x7ff8422a8ce4  (unknown)
    @     0x7ff8422a86e6  (unknown)
    @     0x7ff8422ab687  (unknown)
    @     0x7ff842b17118  caffe::SyncedMemory::to_gpu()
    @     0x7ff842b161f9  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7ff842aeb482  caffe::Blob<>::mutable_gpu_data()
    @     0x7ff842bd1645  caffe::CuDNNConvolutionLayer<>::Forward_gpu()
    @     0x7ff842afd0e2  caffe::Net<>::ForwardFromTo()
    @     0x7ff842afd1f7  caffe::Net<>::Forward()
    @     0x7ff842b8ef1a  caffe::Solver<>::Step()
    @     0x7ff842b8faae  caffe::Solver<>::Solve()
    @           0x40a6f2  train()
    @           0x406478  main
    @     0x7ff84128cf45  (unknown)
    @           0x406c50  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

How can I solve it?
Thank you in advance.

**Comment by Arthur-Shi** [comment]
After I tried my own dataset, and then I change the dataset folders back in /data/VOCdevit.
I cannot train so far, and meet the same problem as shown above. I just change the batch size and GPU number. I am confused. could u help me?

**Comment by sfzhang15** [comment]
@Arthur-Shi 
How do you change the batch size and GPU number?

**Comment by Arthur-Shi** [comment]
/RefineDet/examples/refinedet/VGG16_VOC2007_320.py
gpus = "0"
batch_size = 8
accum_batch_size = 32

**Comment by Arthur-Shi** [comment]
I changed them back, it cannot works any more.

**Comment by Arthur-Shi** [comment]
it's actually a memory problem. I change batch_size=1.
It works.
Thank you so much
